### ISSUE TITLE
.Net: When adding AzureOpenAI chat completion with a custom credential add additional override that accepts a HttpClient

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#4950] opened 2024-02-09 11:06 UTC
One thing we noticed looking at the solution for SK to work with Substrate's LLMApi
 
When using this pattern.
 
 ```
var services = new ServiceCollection();
// Add the kernel and plugins to the service collection.
services.AddKernel();
services.AddAzureOpenAIChatCompletion("gpt-4-turbo", "[https://es365-aoai-eastus2.openai.azure.com/"](https://es365-aoai-eastus2.openai.azure.com/%22), new DefaultAzureCredential(includeInteractiveCredentials: true));
 ```
 
There is not an override that accepts the httpClient.

**Comment by stephentoub** [comment] 2024-02-09 16:25
> There is not an override that accepts the httpClient.

With DI, you typically expect the HttpClient to come from the DI system.  Is that not appropriate for their scenarios? i.e. why would they be getting the SK-related types from DI but not want the HTTP-related components to also come from DI?

**Comment by dmytrostruk** [comment] 2024-02-12 10:46
> With DI, you typically expect the HttpClient to come from the DI system. Is that not appropriate for their scenarios? i.e. why would they be getting the SK-related types from DI but not want the HTTP-related components to also come from DI?

I agree, I also created unit test that verifies that this scenario works as expected:
![Image](https://github.com/microsoft/semantic-kernel/assets/13853051/db492261-bb6d-4b10-904a-ca918c0b1316)

**Comment by dmytrostruk** [comment] 2024-02-22 09:04
Closing this issue as this is by design. See: https://github.com/microsoft/semantic-kernel/issues/5065.

**Closed by dmytrostruk** 2024-02-22 09:04 UTC
Labels: .NET, triage
