### ISSUE TITLE
.Net: Graduate AzureAI OpenAI Embeddings feature

### ISSUE THREAD

**Issue by ekdnam** [microsoft/semantic-kernel#7166] opened 2024-07-09 05:45 UTC
It is in the experimental phase, and I would like to see embeddings being fully integrated into C# SK. 
Is it on the roadmap for being completed soon?

I would have used the Azure.AI.OpenAI API, but it seems it is being developed fast without providing any documentation (atleast as of last week). I think SK will be developed more robustly, so I am betting on y'all!

Let me know if you need any help, thanks

- [ ] Notify PM's and EM's that feature is ready for graduation
- [ ] Contact PM for list of sample use cases
- [ ] Verify there are sample implementations​ for each of the use cases
- [ ] Verify telemetry and logging are complete
- [ ] ​Verify API docs are complete and arrange to have them published
- [ ] Make appropriate updates to Learn docs​
- [ ] Make appropriate updates to Concept samples
- [ ] Make appropriate updates to Blog posts
- [ ] Verify there are no serious open Issues​​
- [ ] Update table in EXPERIMENTS.md
- [ ] Remove SKEXP​ flag from the experimental code

**Comment by matthewbolanos** [comment] 2024-07-09 15:34
Closing as a dupe of [#6618](https://github.com/microsoft/semantic-kernel/issues/6618).

@ekdnam, we currently have this ranked as a P1 issue for "memory" as part of our push to get memory refreshed, we'll be making some adjustments to the embedding interface. We'll be leveraging this ADR: https://github.com/microsoft/semantic-kernel/pull/5277

**Closed by matthewbolanos** 2024-07-09 15:34 UTC
Labels: .NET, triage, feature_graduation
