### ISSUE TITLE
.Net: GetStreamingChatMessageContentsAsync doesn't stream tokens

### ISSUE THREAD

**Issue by JamesPetras** [microsoft/semantic-kernel#5942] opened 2024-04-21 18:27 UTC
**Describe the bug**
Hi guys, I just noticed that SK's GetStreamingChatMessageContentsAsync function doesn't work as expected. 
I just did a prompt to write Little Red Riding Hood in 500 words with ChatGPT 4, and 
the first token came in : 00:00:41.7615917
the last token came in : 00:00:41.7996051

The same prompt, the same instance of OpenAI chatGPT just using GetChatCompletionsStreamingAsync 
The first token came in: 00:00:01.3810466
The last token came in: 00:00:26.6492381

**To Reproduce**
Steps to reproduce the behaviour:
 ```
OpenAIPromptExecutionSettings openAIPromptExecutionSettings = new()
            {
        
                Temperature = 1.0,
                MaxTokens = 4000,
            };
 var time=DateTime.Now;

            var responsekERNEL = chatCompletionService.GetStreamingChatMessageContentsAsync(history, openAIPromptExecutionSettings, kernel);
            bool isFirst=true;
            await foreach (var message in responsekERNEL)
            {
                if (message.Content?.Length > 0)
                {
                    if(isFirst)
                    { 
                     Console.WriteLine($"First token:{DateTime.Now.Subtract(time)}");
                        isFirst=false;
                    }

                    fullMessage += message.Content;
                    Console.Write(message.Content);
                    //Thread.Sleep(100);
                }
            }
```

Non SK call 

  ```
time=DateTime.Now;
            isFirst=true;
            var _client = new OpenAIClient(new Uri(openAiSettings.Endpoint), new AzureKeyCredential(openAiSettings.ApiKey));
             ChatCompletionsOptions chatCompletionsOptions = new()
 {
     DeploymentName = "gpt-4",
     Temperature = 0,

     Messages =
         {
       new ChatRequestSystemMessage(mess)
         }
 };
            var test = _client.GetChatCompletionsStreamingAsync(chatCompletionsOptions);
            string value = "";
            await foreach (var mes in test.Result)
            {
                if (!string.IsNullOrEmpty(mes.ContentUpdate))
                { 
                     if(isFirst)
                    { 
                     Console.WriteLine($"First token - NO SK:{DateTime.Now.Subtract(time)}");
                        isFirst=false;
                    }

                    value += mes.ContentUpdate;
                     Console.Write(mes.ContentUpdate);
                }
            }

              Console.WriteLine($"Last token:{DateTime.Now.Subtract(time)}");
```

**Expected behavior**
I would expect to behave on the sam way as the OpenAI API 

**Screenshots**
Here it is loom https://www.loom.com/share/c71ddd764774468898d2ae38240cfc8f
**Platform**
Microsoft.SemanticKernel 1.7.1
Azure.AI.OpenAI 1.0.0-beta.16

**Comment by RogerBarreto** [comment] 2024-04-29 17:24
The above code is incomplete, although I created a quick application in our latest `1.9.0` version to test  
adding what considered to be missing and wasn't able to reproduce the error as the first token arrived immidiately.

Code used: 
```csharp

using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.ChatCompletion;
using Microsoft.SemanticKernel.Connectors.OpenAI;

OpenAIPromptExecutionSettings openAIPromptExecutionSettings = new()
{
    Temperature = 1.0,
    MaxTokens = 4000,
};

var time = DateTime.Now;

var kernel = Kernel.CreateBuilder().AddOpenAIChatCompletion("gpt-3.5-turbo", "key").Build();
var chatCompletionService = kernel.GetRequiredService<IChatCompletionService>();

var history = new ChatHistory();
history.AddUserMessage("Write me one paragraph what is the origin of Roger name?");

var responsekERNEL = chatCompletionService.GetStreamingChatMessageContentsAsync(history, openAIPromptExecutionSettings, kernel);
bool isFirst = true;
await foreach (var message in responsekERNEL)
{
    if (message.Content?.Length > 0)
    {
        if (isFirst)
        {
            Console.WriteLine($"First token:{DateTime.Now.Subtract(time)}");
            isFirst = false;
        }

        //fullMessage += message.Content;
        Console.Write(message.Content);
        //Thread.Sleep(100);
    }
}

Console.WriteLine($"\nLast token:{DateTime.Now.Subtract(time)}");
```

Result:
```
First token:00:00:01.1017642
The name Roger has Germanic origins and is derived from the Old High German name Hrodgar, composed of the 
elements hrod meaning "fame" and gar meaning "spear". The name was introduced to England by the Normans and 
became popular during the Middle Ages. It was commonly used by English royalty and nobility, with notable 
bearers including Roger de Montgomery, a Norman nobleman and Roger II of Sicily, a medieval king. The name saw 
continued popularity throughout the centuries and remains a classic and timeless choice for boys today.
Last token:00:00:06.2610600
```

I'm closing this issue as this can't be reproduced and seems to be resolved.

**Closed by RogerBarreto** 2024-04-29 17:24 UTC
Labels: .NET
