### ISSUE TITLE
'JsonNumberHandlingAttribute' is only valid on a number or a collection of numbers when applied to a property or field.

### ISSUE THREAD

**Issue by futugyou** [microsoft/semantic-kernel#1129] opened 2023-05-20 13:01 UTC
**Describe the bug**
'JsonNumberHandlingAttribute' is only valid on a number or a collection of numbers when applied to a property or field. 

**To Reproduce**
1.QdrantVectorDbClient.cs Line-132 
```
public async Task<QdrantVectorRecord?> GetVectorByPayloadIdAsync(...)
{
       ... 
       // Line-132
       var data = JsonSerializer.Deserialize<SearchVectorsResponse>(responseContent);
       ...
}
```

**Expected behavior**
'JsonNumberHandlingAttribute' is only valid on a number or a collection of numbers when applied to a property or field. See member 'Id' on type 'Microsoft.SemanticKernel.Connectors.Memory.Qdrant.Http.ApiSchema.SearchVectorsResponse+ScoredPoint'.

**Screenshots**
 
![1](https://github.com/microsoft/semantic-kernel/assets/17871902/7ada5730-51bd-462a-9afb-e10ff7ed997a)

![1](https://github.com/microsoft/semantic-kernel/assets/17871902/75638eff-6039-4103-b329-b1f6b25663f1)

**Comment by craigomatic** [comment] 2023-05-20 14:43
Sorry about this, we brought in a PR last week that was supposed to allow both numbers and strings for that property (Qdrant allows this) and it appears to have caused a regression.

To unblock yourself, you can remove the JsonNumberHandling attribute from ScoredPoint:

<img width="326" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/146438/5f010336-72c0-4c42-92aa-e7bed5465d1a">

We will take another pass at fixing this!

**Comment by tawalke** [comment] 2023-05-20 16:38
@futugyou Are you writing a GUID for your Scored Point ID? 

Qdrant only allows a valid GUID or an int.

**Comment by riccardodangelo** [comment] 2023-05-22 10:45
@tawalke putting a Guid as id, the error doesn't occurs:
 ```
var id1 = Guid.NewGuid().ToString();
 var key1 = await kernel.Memory.SaveInformationAsync(MemoryCollectionName, id: id1, text: "british short hair");
```

**Comment by aaron-puhl** [comment] 2023-05-23 08:54
> @futugyou Are you writing a GUID for your Scored Point ID?
> 
> Qdrant only allows a valid GUID as string or an int. Would you mind sharing an example of your Vector record?
> 
> Cc. @craigomatic

If Qdrant only allows a valid GUID or an int isn't there a problem with saving references?

in MemoryRecord.ReferenceRecord(...):
`new MemoryRecordMetadata
            (
                isReference: true,
                externalSourceName: sourceName,
                id: externalId,
                description: description ?? string.Empty,
                text: string.Empty,
                additionalMetadata: additionalMetadata ?? string.Empty
            ),`
"id: externalId"

**Comment by craigomatic** [comment] 2023-06-02 23:48
PR #1313 was merged and should have resolved this, if you have a moment to verify that would be appreciated

**Comment by SOE-YoungS** [comment] 2023-06-05 12:58
This issue seems to still be occurring in "0.15.230531.5-preview". I've just updated to the latest release & with no other code changes, have just run into this issue.

Id was previously set using strings in our vector db. 

IE:
We're looping though a JSON list of QnA items and saving them into a collection.
The filename in our case, is named to represent the team / process the QnA list targets.

``` await _memory.SaveInformationAsync("QnACollection", qnaItem, $"{file.Name}-q{i}"); ```

Not sure if we need to change anything here, but my understanding of QDrant is that a string value or an int should be accepted.

**Comment by craigomatic** [comment] 2023-06-05 13:26
You may need to use a guid for the id see https://github.com/microsoft/semantic-kernel/issues/794#issuecomment-1533797386

The next step in improving qdrant support is to add guid validation when a string is used as the id

**Comment by aaron-puhl** [comment] 2023-06-05 13:38
The id in "SaveInformationAsync" is not used as the id in Qdrant. See in QdrantMemoryStore:

```
var existingRecord = await this._qdrantClient.GetVectorByPayloadIdAsync(
                    collectionName,
                    record.Metadata.Id,
                    cancellationToken: cancellationToken)
                .ConfigureAwait(false);

if (existingRecord != null)
{
    pointId = existingRecord.PointId;
}
```

where "record.Metadata.Id" is the id from SaveInformationAsync if i did not miss something.

**Comment by SOE-YoungS** [comment] 2023-06-05 15:32
> You may need to use a guid for the id see [#794 (comment)](https://github.com/microsoft/semantic-kernel/issues/794#issuecomment-1533797386)
> 
> The next step in improving qdrant support is to add guid validation when a string is used as the id

Ok, so fortunately I'm in a position I can clear the vector DB and rebuild the data stored.

However, the following code is still throwing this error in the latest nuget package.

``` 
var id = Guid.NewGuid().ToString();
await _memory.SaveInformationAsync("QnACollection", qnaItem, id, description: $"{file.Name}-q{i}");
```

**Comment by smandava** [comment] 2023-06-09 14:24
Looks like the 

> ed and should have resolved this, if you have a moment to verify that would be appre

@craigomatic, The [copilot chat app sample](https://github.com/microsoft/semantic-kernel/blob/f4e92eb1de8c8e222c51e0fd8e46e0e6be5650b7/samples/apps/copilot-chat-app/webapi/CopilotChat/Controllers/DocumentImportController.cs#L213)  is giving the same error. The project is using SK version [0.15.230531.5-preview](https://github.com/microsoft/semantic-kernel/blob/f4e92eb1de8c8e222c51e0fd8e46e0e6be5650b7/samples/apps/copilot-chat-app/webapi/CopilotChatWebApi.csproj#LL14C67-L14C88). Please share if there is a work around for the copilot chat app sample to make with work with Qdrant. 

Stack trace:

>          at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
>          at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>          at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
>          at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
>          at Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantVectorDbClient.GetVectorByPayloadIdAsync(String collectionName, String metadataId, Boolean withVector, CancellationToken cancellationToken)
>          at Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantMemoryStore.ConvertFromMemoryRecordAsync(String collectionName, MemoryRecord record, CancellationToken cancellationToken)
>          at Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantMemoryStore.UpsertAsync(String collectionName, MemoryRecord record, CancellationToken cancellationToken)
>          at Microsoft.SemanticKernel.Memory.SemanticTextMemory.SaveInformationAsync(String collection, String text, String id, String description, String additionalMetadata, CancellationToken cancellationToken)
>          at SemanticKernel.Service.CopilotChat.Controllers.DocumentImportController.ParseDocumentContentToMemoryAsync(IKernel kernel, String content, DocumentImportForm documentImportForm, String memorySourceId) in /workspaces/semantic-kernel/samples/apps/copilot-chat-app/webapi/CopilotChat/Controllers/DocumentImportController.cs:line 213
>          at SemanticKernel.Service.CopilotChat.Controllers.DocumentImportController.ImportDocumentAsync(IKernel kernel, DocumentImportForm documentImportForm) in /workspaces/semantic-kernel/samples/apps/copilot-chat-app/webapi/CopilotChat/Controllers/DocumentImportController.cs:line 128
>          at SemanticKernel.Service.CopilotChat.Controllers.DocumentImportController.ImportDocumentAsync(IKernel kernel, DocumentImportForm documentImportForm) in /workspaces/semantic-kernel/samples/apps/copilot-chat-app/webapi/CopilotChat/Controllers/DocumentImportController.cs:line 133

**Comment by craigomatic** [comment] 2023-06-09 23:17
Try updating to the latest nuget that was just released: https://www.nuget.org/packages/Microsoft.SemanticKernel/0.15.230609.2-preview

**Comment by smandava** [comment] 2023-06-10 04:15
> Try updating to the latest nuget that was just released: https://www.nuget.org/packages/Microsoft.SemanticKernel/0.15.230609.2-preview

Worked! Thank you.

**Closed** 2023-06-10 14:21 UTC
Labels: memory
