### ISSUE TITLE
Function inputs and escaping special characters with Unicode

### ISSUE THREAD

**Issue by sophialagerkranspandey** [microsoft/semantic-kernel#7365] opened 2024-07-19 15:40 UTC
### Discussed in https://github.com/microsoft/semantic-kernel/discussions/7308

<div type='discussions-op-text'>

<sup>Originally posted by **glorious-beard** July 16, 2024</sup>
If I set a kernel argument to content containing special characters, (HTML tags, for example), and I look at the logger output from the kernel when it's invoking the function, I notice that the JSON object escapes all of the special character.

For example, if I set "input" to `<p>Version 1.2</p>....`, the function argument looks like:
```json
{"input":"\u003Cp\u003EVersion 1.2\u003C/p\u003E..."}
```

Two questions:
1. Do the extra characters in escaping "<" and ">" with 5 additional characters incur extra token cost?
2. Does the function call unescape these characters before it is sent to the LLM endpoint?
</div>

**Comment by matthewbolanos** [comment] 2024-07-19 15:49
I'm pretty sure that the characters are _only_ encoded so we can print the log statement (so it shouldn't impact your logic), but adding folks to verify.

**Comment by eavanvalkenburg** [comment] 2024-07-22 08:32
In python, I can confirm, they are unescaped before being sent to the model, this happens within the from_element method for chat, and within the _invoke_internal method for text, hence it also does not add extra tokens (although tokenization on the model side might)

**Comment by markwallace-microsoft** [comment] 2024-07-24 12:37
We have protection to prevent prompt injection attacks which will encode potentially dangerous tags. If you trust the content you can change this behaviour, take a look at this sample to see the available options: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/Concepts/ChatPrompts/SafeChatPrompts.cs

**Comment by matthewbolanos** [comment] 2024-07-26 15:46
Closing this issue since it's handled in both C# and Python

**Closed by matthewbolanos** 2024-07-26 15:46 UTC
Labels: triage
