### ISSUE TITLE
.Net: Support complex function parameters when using OpenAIFunction calling

### ISSUE THREAD

**Issue by frederikrosenberg** [microsoft/semantic-kernel#3126] opened 2023-10-11 10:42 UTC
It is currently impossible to have complex objects in the function parameters using `OpenAIFunction` and `OpenAIFunctionParameter`.

The following JSON is a valid request but can not currently be represented using the above classes.

```json
{
  "temperature":0.7,
  "top_p":0.95,
  "frequency_penalty":0,
  "presence_penalty":0,
  "max_tokens":800,
  "messages":[
     {
        "role":"user",
        "content":"What is the weather like in Boston?"
     }
  ],
  "functions":[
     {
        "name":"get_current_weather",
        "description":"Get the current weather in a given location",
        "parameters":{
           "required":[
              "city"
           ],
           "type":"object",
           "properties":{
              "city":{
                 "required":[
                    "name",
                    "country"
                 ],
                 "type":"object",
                 "properties":{
                    "name":{
                       "type":"string"
                    },
                    "country":{
                       "type":"string"
                    }
                 }
              }
           }
        }
     }
  ],
  "function_call":"auto"
}
 ```

Arrays are also not supported.

**Comment by cloudscool** [comment] 2023-10-11 11:58
Hello frederikrosenberg, you can consider using Native Functions to handle your needs, if it is just a simple ingress, consider using Semantic Functions

**Comment by SergeyMenshykh** [comment] 2024-01-26 14:43
Hi @frederikrosenberg, thanks for reporting the issue. We are working on fix for the similar issue - https://github.com/microsoft/semantic-kernel/issues/4696 at the moment. The issue you have might have the same root cause and can be addressed by the fix.

In case you think this issue if different please send us code example that demonstrates the problem.

**Comment by frederikrosenberg** [comment] 2024-01-29 08:47
Hi @SergeyMenshykh, it looks like it is related. I have created a code example just to be sure:

Program.cs
```csharp
using AITest;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Connectors.OpenAI;

var kernelBuilder = Kernel.CreateBuilder();
kernelBuilder.AddAzureOpenAIChatCompletion(...); // using GPT-4-turbo

kernelBuilder.Services.AddLogging(builder => builder.AddConsole());
kernelBuilder.Plugins.AddFromType<WeatherPlugin>("weather");
var kernel = kernelBuilder.Build();

Console.WriteLine(kernel.Plugins.First().First().Metadata.Parameters.First().Schema);

var settings = new OpenAIPromptExecutionSettings
    { ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions };

var result = await kernel.InvokePromptAsync("What is the weather in Odense?", new KernelArguments(settings));

Console.WriteLine(result);
```

WeatherPlugin.cs
```csharp
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.SemanticKernel;

namespace AITest;

public class WeatherPlugin
{
    [KernelFunction]
    [Description("Get weather in city.")]
    public Task<string> GetWeatherAsync(WeatherParameters parameters)
    {
        return Task.FromResult($"The weather in {parameters.City.Name} ({parameters.City.Country}) is sunny");
    }
}

public record WeatherParameters(City City);

public class City
{
    [Required] 
    public string Name { get; set; } = string.Empty;
    public string? Country { get; set; }
}
```

AITest.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoWarn>SKEXP0042</NoWarn>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
      <PackageReference Include="Microsoft.SemanticKernel" Version="1.2.0" />
      <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.2.0" />
    </ItemGroup>
</Project>
````

Output:
```text
{                         
  "type": "object",       
  "properties": {         
    "City": {             
      "type": "object",   
      "properties": {     
        "Name": {         
          "type": "string"
        },                
        "Country": {      
          "type": "string"
        }                 
      }                   
    }                     
  }                       
}                         
info: func73a34db732234af59c72870a0d485f76[0]                
      Function func73a34db732234af59c72870a0d485f76 invoking.
info: Microsoft.SemanticKernel.Connectors.OpenAI.AzureOpenAIChatCompletionService[0]
      Prompt tokens: 60. Completion tokens: 21. Total tokens: 81.
info: GetWeather[0]
      Function GetWeather invoking.
fail: GetWeather[0]
      Function failed. Error: Object of type 'System.String' cannot be converted to type 'AITest.WeatherParameters'.
      System.ArgumentException: Object of type 'System.String' cannot be converted to type 'AITest.WeatherParameters'.
         at System.RuntimeType.CheckValue(Object& value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
         at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.SemanticKernel.KernelFunctionFromMethod.Invoke(MethodInfo method, Object target, Object[] arguments)
         at Microsoft.SemanticKernel.KernelFunctionFromMethod.<>c__DisplayClass9_0.<GetMethodDetails>g__Function|0(Kernel kernel, KernelFunction function, KernelArguments arguments, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.KernelFunctionFromMethod.InvokeCoreAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.KernelFunction.InvokeAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken)
info: GetWeather[0]
      Function completed. Duration: 0.0106568s
info: Microsoft.SemanticKernel.Connectors.OpenAI.AzureOpenAIChatCompletionService[0]
      Prompt tokens: 116. Completion tokens: 65. Total tokens: 181.
```

Notice the parameter JSON schema. It does not include the required fields.
The AI responds with the correct argument (extracted using debug)

Parameter values from the AI:
```json
{
  "parameters": {
    "City": {
      "Name": "Odense",
      "Country": "Denmark"
    }
  }
}
```

**Closed** 2024-02-06 13:33 UTC
Labels: .NET, kernel, vnext

**Comment by ekjuanrejon** [comment] 2025-02-06 20:56
I'm using the latest version of semantic kernel and i have that error:

` Object of type 'System.String' cannot be converted to type`
