### ISSUE TITLE
Python sample notebook05 > stepwise planner > Variable `$agent_scratch_pad` not found

### ISSUE THREAD

**Issue by skim0011** [microsoft/semantic-kernel#4772] opened 2024-01-29 09:10 UTC
![image](https://github.com/microsoft/semantic-kernel/assets/156260712/44932cc4-6b78-42fd-b36b-2d9a7318d508)

I'm not sure if this is bing's problem or planner's internal function problem. Is anyone having a similar issue?

**Comment by jameshiggie** [comment] 2024-01-30 07:17
I experienced this as well. Also getting significant worst results after trying to update from V0.4.0

![image](https://github.com/microsoft/semantic-kernel/assets/5995501/48811aa6-bbf2-49b7-b622-78b67961aa44)

**Comment by Timothyhuiyukfai** [comment] 2024-01-31 13:33
I was having the same issue and the planner is not able to display its step of thought either
![image](https://github.com/microsoft/semantic-kernel/assets/53361830/324537fa-2c93-41ec-821d-2d1f6eaefec6)

**Comment by moonbox3** [comment] 2024-02-05 21:50
The log statement "Variable `$agent_scatch_pad` not found" is purely a warning and isn't an issue. The reason it is appearing now is because the logging was updated to use the Python logging module. The warning was always there but was masked before due to logging needed to be configured per class. Note: if you were to run the 00 sample notebook or the joke kernel example, you would also something like: "Variable `$style` not found". If you provided the style context as part of the input, that logging warning wouldn't appear.

With regards to the "worse results" you're seeing from the planner -- you'll need to please give more details about the exact error you're experiencing, preferably in a separate issue so it is easier to track. Please include sample code, screenshots, or any other information that would allow us to investigate it efficiently and thoroughly. Thanks!

**Comment by moonbox3** [comment] 2024-02-26 17:38
Closing this issue as this was by design for this planner. We're working on a FunctionCallingStepwisePlanner for v1, which will in turn deprecate old planners.

**Closed by moonbox3** 2024-02-26 17:38 UTC
Labels: python
