### ISSUE TITLE
.Net: Add Support for Surfacing HTTP Verb for Function Calls in Semantic Kernel

### ISSUE THREAD

**Issue by lemillermicrosoft** [microsoft/semantic-kernel#5694] opened 2024-03-28 17:17 UTC
### Description
We would like to request the addition of support for surfacing the HTTP verb (e.g., GET, POST, PUT, etc.) for function calls in Semantic Kernel when working with OpenAPI specifications. This feature is needed to help keep humans in the loop and show action confirmations, such as prompting the user for confirmation when a POST request is made.  

### Proposed Changes  
1. Update the parsing process in Semantic Kernel to recognize and store the HTTP verb associated with each operation in the OpenAPI specification.  
2. Update the generated function models to include a property indicating the HTTP verb of the operation.  

or

1. Update the parsing process in Semantic Kernel to recognize the HTTP verb associated with each operation in the OpenAPI specification and take in an optional list of 'consequential' HTTP verbs at parsing.
2. Update the generated function model to include a property indicating whether the function is 'consequential' and uses the HTTP verb and configuration at parsing time.

or

1. _other_
  
  
### Additional Considerations  
The existing issue for adding support for the x-openai-isConsequential property in Semantic Kernel (Issue #5506).  
  
Thank you for considering this feature request. We believe that adding support for surfacing the HTTP verb for function calls in Semantic Kernel will enhance the overall capabilities of the platform and provide a more consistent experience for users interacting with actions.

**Comment by SergeyMenshykh** [comment] 2024-06-12 11:21
I believe the issue is resolved by this PR - https://github.com/microsoft/semantic-kernel/pull/5911 and can be closed. Please reopen it if it is not.

**Closed** 2024-06-12 11:21 UTC
Labels: .NET
