### ISSUE TITLE
No deserialization from string to types

### ISSUE THREAD

**Issue by sanchez** [microsoft/semantic-kernel#4074] opened 2023-12-07 07:07 UTC
**Describe the bug**
Currently if a custom type is used as the return type then it will correctly appear with a schema in the HandleBars Prompt for the Plan, and if the type is returned from a native function then it is also correctly serialized and returned. However if the custom type is used as an input to a native function then a `System.ArgumentException` is thrown with the message of `Object of type 'System.String' cannot be converted to type 'Plugins.Geometry.PointPlugin+AIPoint3d'.`

**To Reproduce**
Create two native functions with a custom POCO type as the return from one and input to the other. Write a prompt which should require returning the POCO and passing it as an input to the other function.

**Expected behavior**
Serialization and Deserialization should happen for the POCO type natively. If I switch the input to be a string then the type in HandleBars also changes and I lose type assistance for the planner.

**Comment by sanchez** [comment] 2023-12-07 07:08
.NET, RC3

**Comment by SergeyMenshykh** [comment] 2023-12-08 13:08
Hi @sanchez , thanks for reporting the issue. To help solve it quickly, please share some code examples or a console app that shows the problem. This will make it easier to understand and fix it faster.

**Comment by sanchez** [comment] 2023-12-13 04:35
[semantic-learning.zip](https://github.com/microsoft/semantic-kernel/files/13656011/semantic-learning.zip)

Sorry for the delay in a response, I have attached some example code to this comment here, in the example here you try to execute the prompt `create a new point with the values X=5, Y=3, Z=1. What is the length of newPoint?` then an ArgumentException is thrown because the type is not deserialized to AIPoint3d on step 2.

**Comment by SergeyMenshykh** [comment] 2023-12-13 23:40
@sanchez thanks for sharing the console app, as it allowed me to easily run your example. I've run it on the latest SK, which as of today is [RC4](https://www.nuget.org/packages/Microsoft.SemanticKernel/), and it works well. We have recently improved the method parameters and result marshaling functionality, so the issue you experienced must have been fixed. Please get the latest version of SK and confirm whether the issue has been resolved. 
A few screenshots:

`ConstructPoint` function call:
<img width="661" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/68852919/48b39835-7b93-4e20-8baa-2743580f95ca">
 
`GetLength` function call:
<img width="683" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/68852919/6763da37-2b8d-4076-9023-6c04ed4a1941">

Result:
<img width="676" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/68852919/39145cb0-3985-4ef6-a7b5-dcde443efcc8">

**Comment by sanchez** [comment] 2023-12-14 00:58
@SergeyMenshykh other than setting the package version to use RC4, are there any other changes I need to make? I still get the same exception:

![image](https://github.com/microsoft/semantic-kernel/assets/5264697/8945ec23-3e21-478e-b6bc-367a2f3ae6f3)

**Comment by sanchez** [comment] 2023-12-14 03:20
Sorry, I have just realized I have not been using RC4 because of #4257 and the code automatically rolled back to RC3

**Comment by SergeyMenshykh** [comment] 2023-12-14 12:20
Closing the issue for now, assuming the problem is resolved. Feel free to reopen it if that's not the case.

**Closed by SergeyMenshykh** 2023-12-14 12:20 UTC
Labels: triage, v1 bugbash
