### ISSUE TITLE
.Net: Add changes to the values of the plan parameters while the  HandlebarsPlan  is running

### ISSUE THREAD

**Issue by strikene** [microsoft/semantic-kernel#4293] opened 2023-12-15 04:43 UTC
Env: RC4 .NET Core 7
Here is my code 
string handlbar_plan = "{{!-- Step 1: Set the generate_analysis_report variable --}}\n" +
       "{{set \"generate_analysis_report\" \"$generate_analysis_report\"}}" +
       "\n\n" +
       "{{!-- Step 2: Create a file name for the report --}}\n" +
       "{{set \"file_name\" (concat \"generate_analysis_report_\" \".txt\")}}" +
       "\n\n" +
       "{{!-- Step 3: Save the generate_analysis_report content to a local file --}}" +
       "\n" +
       "{{ExtenedFilePlugin-WriteFileContent content=(get \"generate_analysis_report\") path=(get \"file_name\")}}" +
       "\n\n" +
       "{{!-- Step 4: Upload the local file to OneDrive --}}" +
       "\n" +
       "{{OneDrive-UploadFile filePath=(get \"file_name\") destinationPath=(concat \"/OneDriveFolder/\" (get \"file_name\"))}}" +
       "\n\n" +
       "{{!-- Step 5: Output the result --}}" +
       "\n" +
       "{{json \"The analysis report has been saved to OneDrive.\"}}";

HandlebarsPlan reloadedPlan = new HandlebarsPlan(handlbar_plan, "");
var reloadedPlan_re  = await reloadedPlan.InvokeAsync(sk._SK_Kernel, new KernelArguments()
{
    ["$generate_analysis_report"]="1111"
    ["generate_analysis_report"]="1111"
});

The plan has a parameter named "generate_analysis_report" .I haven't found any way to change this value at runtime

**Comment by teresaqhoang** [comment] 2023-12-16 00:06
Hey @strikene, what are you using as the goal for the plan? Or are you just trying to load your own plan and run that?

Either way, you can load the variables into the KernelArgs using this syntax:
```
        HandlebarsPlan reloadedPlan = new HandlebarsPlan(handlebars_plan, "");
        var reloadedPlan_re = await reloadedPlan.InvokeAsync(sk._SK_Kernel, new KernelArguments()
        {
            { "generate_analysis_report", "1111" }
        });
```

Note:
- When referencing a variable, you don't need to prefix it with `$`. It can just be `generate_analysis_report`, so the first step would be: `"{{set "generate_analysis_report" "$generate_analysis_report"}}"`
- The variables referenced in the Handlebars prompt template must match with the keys defined in the KernelArguments dictionary, so if you want to keep the `$`, the KernelArguments entry would be `{ "$generate_analysis_report", "1111" }`

**Comment by strikene** [comment] 2023-12-16 04:56
> Hey @strikene, what are you using as the goal for the plan? Or are you just trying to load your own plan and run that?
> 
> Either way, you can load the variables into the KernelArgs using this syntax:
> 
> ```
>         HandlebarsPlan reloadedPlan = new HandlebarsPlan(handlebars_plan, "");
>         var reloadedPlan_re = await reloadedPlan.InvokeAsync(sk._SK_Kernel, new KernelArguments()
>         {
>             { "generate_analysis_report", "1111" }
>         });
> ```
> 
> Note:
> 
> * When referencing a variable, you don't need to prefix it with . It can just be , so the first step would be: `$``generate_analysis_report``"{{set "generate_analysis_report" "$generate_analysis_report"}}"`
> * The variables referenced in the Handlebars prompt template must match with the keys defined in the KernelArguments dictionary, so if you want to keep the , the KernelArguments entry would be `$``{ "$generate_analysis_report", "1111" }`

Thanks for the help, I'll try it later~

In my case, goal is a single step after a complex step decomposition, and we try to break down the complex action into simpler, atomic-level steps through the prompt word, so as to ensure that the planner chooses the function as little as possible without "illusion"  

 The variable $generate_analysis_report is the result of the previous step referenced by the current step, and this method works reliably. In the previous sequence planner we could easily pass it on.

**Comment by strikene** [comment] 2023-12-16 06:32
> Hey @strikene, what are you using as the goal for the plan? Or are you just trying to load your own plan and run that?
> 
> Either way, you can load the variables into the KernelArgs using this syntax:
> 
> ```
>         HandlebarsPlan reloadedPlan = new HandlebarsPlan(handlebars_plan, "");
>         var reloadedPlan_re = await reloadedPlan.InvokeAsync(sk._SK_Kernel, new KernelArguments()
>         {
>             { "generate_analysis_report", "1111" }
>         });
> ```
> 
> Note:
> 
> * When referencing a variable, you don't need to prefix it with . It can just be , so the first step would be: `$``generate_analysis_report``"{{set "generate_analysis_report" "$generate_analysis_report"}}"`
> * The variables referenced in the Handlebars prompt template must match with the keys defined in the KernelArguments dictionary, so if you want to keep the , the KernelArguments entry would be `$``{ "$generate_analysis_report", "1111" }`

I have come up with the test results
1."{{set "generate_analysis_report" "XXXXXX"}}"      No matter which way I use it in the arguments, I can't change the value of this variable at runtime (in my case, generate_analysis_report writes the contents as a file to the local file, so it's good to judge)


2."{{set "$generate_analysis_report" "XXXXXX"}}"  
using  KernelArguments saved_handlbar_plan_arguments = new()
 {
     { "generate_analysis_report", "1111" }
 };  it works . but  ‘{{set "generate_analysis_report" "XXXXXX"}}’ **it create by planner . I can't interfere** with the planner generating variables with the '$' prefix, so I can't change their values

**Comment by strikene** [comment] 2023-12-16 06:33
> > Hey @strikene, what are you using as the goal for the plan? Or are you just trying to load your own plan and run that?
> > Either way, you can load the variables into the KernelArgs using this syntax:
> > ```
> >         HandlebarsPlan reloadedPlan = new HandlebarsPlan(handlebars_plan, "");
> >         var reloadedPlan_re = await reloadedPlan.InvokeAsync(sk._SK_Kernel, new KernelArguments()
> >         {
> >             { "generate_analysis_report", "1111" }
> >         });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Note:
> > 
> > * When referencing a variable, you don't need to prefix it with . It can just be , so the first step would be: `` $``generate_analysis_report``"{{set "generate_analysis_report" "$generate_analysis_report"}}" ``
> > * The variables referenced in the Handlebars prompt template must match with the keys defined in the KernelArguments dictionary, so if you want to keep the , the KernelArguments entry would be `` $``{ "$generate_analysis_report", "1111" } ``
> 
@teresaqhoang 
> I have come up with the test results 1."{{set "generate_analysis_report" "XXXXXX"}}" No matter which way I use it in the arguments, I can't change the value of this variable at runtime (in my case, generate_analysis_report writes the contents as a file to the local file, so it's good to judge)
> 
> 2."{{set "$generate_analysis_report" "XXXXXX"}}" using KernelArguments saved_handlbar_plan_arguments = new() { { "generate_analysis_report", "1111" } }; it works . but ‘{{set "generate_analysis_report" "XXXXXX"}}’ **it create by planner . I can't interfere** with the planner generating variables with the '$' prefix, so I can't change their values

**Comment by strikene** [comment] 2023-12-16 06:34
> Hey @strikene, what are you using as the goal for the plan? Or are you just trying to load your own plan and run that?
> 
> Either way, you can load the variables into the KernelArgs using this syntax:
> 
> ```
>         HandlebarsPlan reloadedPlan = new HandlebarsPlan(handlebars_plan, "");
>         var reloadedPlan_re = await reloadedPlan.InvokeAsync(sk._SK_Kernel, new KernelArguments()
>         {
>             { "generate_analysis_report", "1111" }
>         });
> ```
> 
> Note:
> 
> * When referencing a variable, you don't need to prefix it with . It can just be , so the first step would be: `$``generate_analysis_report``"{{set "generate_analysis_report" "$generate_analysis_report"}}"`
> * The variables referenced in the Handlebars prompt template must match with the keys defined in the KernelArguments dictionary, so if you want to keep the , the KernelArguments entry would be `$``{ "$generate_analysis_report", "1111" }`

@teresaqhoang 



I have come up with the test results
1."{{set "generate_analysis_report" "XXXXXX"}}" No matter which way I use it in the arguments, I can't change the value of this variable at runtime (in my case, generate_analysis_report writes the contents as a file to the local file, so it's good to judge)

2."{{set "$generate_analysis_report" "XXXXXX"}}"
using KernelArguments saved_handlbar_plan_arguments = new()
{
{ "generate_analysis_report", "1111" }
}; it works . but ‘{{set "generate_analysis_report" "XXXXXX"}}’ it create by planner . I can't interfere with the planner generating variables with the '$' prefix, so I can't change their values

**Comment by teresaqhoang** [comment] 2023-12-22 01:44
Related to https://github.com/microsoft/semantic-kernel/issues/4072, @matthewbolanos we should consider if and how to expose initial variables to the planner. 

Added variable access testing to this issue here: https://github.com/microsoft/semantic-kernel/issues/4252

**Comment by matthewbolanos** [comment] 2024-02-01 19:14
Closing as a dupe of #4422

**Closed by matthewbolanos** 2024-02-01 19:14 UTC
Labels: .NET, planner
