### ISSUE TITLE
Allow httpskill to accept optional headers

### ISSUE THREAD

**Issue by sruthirameshv** [microsoft/semantic-kernel#1690] opened 2023-06-23 00:47 UTC
Httpskill currently doesnt allow callers to add additional headers . For instance , if the user wants to pass bearer token to the post call ,
user should be able to pass the bearer token via context variable to the httpskill.

If this is an acceptable feature , I am happy to make the change.

In reference to now deleted issue: https://github.com/microsoft/semantic-kernel/issues/1567

```[tasklist]
### Tasks
```

**Comment by alexchaomander** [comment] 2023-06-26 03:39
@shawncal @dluc @adrianwyatt Can you comment on this?

**Comment by nacharya1** [comment] 2023-08-24 22:08
@sruthirameshv - let me know if you are still interested to work on this? Would love to see a pr or contribution to https://github.com/microsoft/semantic-kernel/issues/1567

**Comment by lemillermicrosoft** [comment] 2023-09-08 20:14
Closing as duplicate of #1567

**Closed by lemillermicrosoft** 2023-09-08 20:14 UTC
Labels: enhancement, python, core plugin
