### ISSUE TITLE
.Net 4V识别图片出错

### ISSUE THREAD

**Issue by 2023pfm** [microsoft/semantic-kernel#6348] opened 2024-05-21 02:56 UTC
您好，我参考你们提供的例子，我在使用4V解释图片时出错，报错：Method not found: 'Void Azure.AI.OpenAI.ChatMessageImageContentItem..ctor(System.Uri)'.

我代码如下：

const string ImageUri = "https://upload.wikimedia.org/wikipedia/commons/d/d5/Half-timbered_mansion%2C_Zirkel%2C_East_view.jpg";

var kernel = Kernel.CreateBuilder()
    .AddOpenAIChatCompletion("gpt-4-vision-preview", "")
    .Build();

var chatCompletionService = kernel.GetRequiredService<IChatCompletionService>();

var chatHistory = new ChatHistory("You are a friendly assistant.");

chatHistory.AddUserMessage(
[
    new TextContent("What’s in this image?"),
new ImageContent(new Uri(ImageUri))
]);

var reply = chatCompletionService.GetChatMessageContentAsync(chatHistory).Result;

Console.WriteLine(reply.Content);

![image](https://github.com/microsoft/semantic-kernel/assets/133073974/9b978ac8-6ed8-43a8-b161-941fdde4a2ba)

**Comment by 2023pfm** [comment] 2024-05-21 03:42
我应用了AutoGen的0.0.13的包和Microsoft.SemanticKernel的1.13.0的包，里面引用的Azure OpenAI的包不一样，有没有可能是这种情况导致的
AutoGen的0.0.13的包引用的是Azure.AI.OpenAI的1.0.0-beta.17
Microsoft.SemanticKernel的1.13.0的包引用的是Azure.AI.OpenAI的1.0.0-beta.15

**Comment by feiyun0112** [comment] 2024-05-23 01:28
请提供一个示例项目以便重现问题

**Comment by 2023pfm** [comment] 2024-05-23 01:49
你好，我们这边已经解决了，是因为SK最新包的引用Azure.AI.OpenAI没有升级的原因，Autogen最新的Azure.AI.OpenAI的包是用的Azure.AI.OpenAI的1.0.0-beta.17。

发件人: feiyun0112 ***@***.***>
发送时间: 2024年5月23日 9:29
收件人: microsoft/semantic-kernel ***@***.***>
抄送: 彭方敏 ***@***.***>; Author ***@***.***>
主题: Re: [microsoft/semantic-kernel] .Net 4V识别图片出错 (Issue #6348)


请提供一个示例项目以便重现问题

―

**Comment by markwallace-microsoft** [comment] 2024-06-10 08:09
Translation of comments:

_I used the AutoGen 0.0.13 package and the Microsoft.SemanticKernel 1.13.0 package, which reference different Azure OpenAI packages. Is it possible that this situation caused the issue?
The AutoGen 0.0.13 package references Azure.AI.OpenAI 1.0.0-beta.17.
The Microsoft.SemanticKernel 1.13.0 package references Azure.AI.OpenAI 1.0.0-beta.15.

To reproduce the issue, please provide a sample project.

Hello, we have solved the issue. The problem was caused by the SK package not being updated to use the latest Azure.AI.OpenAI reference. Autogen's latest Azure.AI.OpenAI package uses Azure.AI.OpenAI 1.0.0-beta.17._

Closing as the issue has been resolved

**Closed by markwallace-microsoft** 2024-06-10 08:09 UTC
Labels: .NET, triage
