### ISSUE TITLE
Python: Adding MongoDB Atlas Vector Search as a datastore

### ISSUE THREAD

**Issue by prakul** [microsoft/semantic-kernel#2591] opened 2023-08-27 03:31 UTC
MongoDB Atlas has support for efficiently storing, indexing and querying high-dimensional vector embeddings - https://www.mongodb.com/products/platform/atlas-vector-search. We will be adding support for python and C# Memory connectors for Microsoft Semantic Kernel.

**Comment by kshitijcode** [comment] 2023-08-28 04:45
@prakul Its WIP https://github.com/microsoft/semantic-kernel/pull/2560

**Comment by nacharya1** [comment] 2023-08-28 16:33
Closing this as a dupe of #2375

**Comment by prakul** [comment] 2023-08-28 17:10
@kshitijcode The "MongoDB Atlas Vector Search" and "Azure CosmosDB for MongoDB" are different products, as I understand. For instance the template provided for creating index in Azure CosmosDB is referred below, (which is different from MongoDB). Do you plan to test & release  for both or just Azure CosmosDB? Do you plan this for python, c# or both?

Index creation template in Azure CosmosDB:
{
  "createIndexes": "<collection_name>",
  "indexes": [
    {
      "name": "<index_name>",
      "key": {
        "<path_to_property>": "cosmosSearch"
      },
      "cosmosSearchOptions": {
        "kind": "vector-ivf",
        "numLists": <integer_value>,
        "similarity": "<string_value>",
        "dimensions": <integer_value>
      }
    }
  ]
}

Index Creation template in MongoDB:
{
  "mappings": {
    "dynamic": true|false,
    "fields": {
      "<field-name>": {
        "type": "knnVector",
        "dimensions": <number-of-dimensions>,
        "similarity": "euclidean | cosine | dotProduct"
      }
    }
  }
}
https://www.mongodb.com/docs/atlas/atlas-search/field-types/knn-vector/

**Comment by prakul** [comment] 2023-08-29 07:10
@nacharya1 @kshitijcode @shawncal   This is not a duplicate of #2375 

Azure Cosmos DB and MongoDB are separate products which are owned by different companies. Azure cosmosDB from Microsoft provides a MongoDB compatible API, but does not represents MongoDB - https://www.mongodb.com/mongodb-vs-cosmos-db . 

Azure Cosmos DB also supports PostgreSQL, and Apache Cassandra which have a vector database offering of their own and Azure CosmosDB may choose to expose the vector db functionality for them as well in the future. wIll you combine Postgres (https://github.com/microsoft/semantic-kernel/tree/main/python/semantic_kernel/connectors/memory/postgres) Semantic Kernel integration with Azure CosmosDB as well?

MongoDB is a standalone product which 
1) has a separate representation in frameworks like LangChain (https://python.langchain.com/docs/integrations/vectorstores/mongodb_atlas) and LlamaIndex (https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/MongoDBAtlasVectorSearch.html)

2) is Incompatible with Azure Cosmos DB: There is a significant difference is both products, please refer to the semantics of index creation as given in the comment above.

By representing 2 separate products as one creates confusion and leads to bad user experience. The [PR](https://github.com/microsoft/semantic-kernel/pull/2560/files#diff-b165a067b86131ac682b85ef035607c6c7f836f4498a1557a31da314ffe70616R32-R33) mentions a api_type parameter (with options azuremongodb and mongodbatlas) which is defaulting to Azure. Apart from being factually and semantically incorrect (API type of mongodbatlas does not stand for anything since Atlas is MongoDB), this seems highly problematic to me as there might be a situation where our customer starts using this expecting it to be MongoDB and get confused when the product doesn't work as expected, since its defaulting to Azure CosmosDB.

The scope of [PR #2560](https://github.com/microsoft/semantic-kernel/pull/2560) should be restricted to Azure CosmosDB, which was the original intent of the issue #2375 (Adding Azure CosmosDB Mongo vCore as a datastore). MongoDB should be a separate integration, just like Postgres and others.

**Comment by prakul** [comment] 2023-08-29 07:32
@kshitijcode Who all are included in this "we"? Where are these discussions happening? Can we find a time to discuss this over zoom, if possible? Would really love to understand more.

**Comment by prakul** [comment] 2023-09-14 04:49
Added a .Net ticket as per our discussion today - https://github.com/microsoft/semantic-kernel/issues/2817

**Closed** 2023-10-02 21:34 UTC
Labels: python, memory, connector
