### ISSUE TITLE
.Net: For Automatic Function Calling, there should be filters to control the loop behavior

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#5470] opened 2024-03-14 02:15 UTC
Today, we have filters for prompt rendering and function invoking. What's missing is the ability to control the behavior while inside of the automatic function call loop. While in the loop, the user should be able to break out of the loop in the following scenarios:

- **End before the LLM generates a final message** – Many customers are wanting the LLM to return back the JSON of a function call for an adapative card or verbatims from a RAG search result. Unfortunately, this is not possible today because the last step is to always have the LLM generate a message that is returned back to the user. With filters, the developer would be able to break out of the loop before this final step and return the JSON payload.
- **End after N-number of loops** – To avoid an infinite loop, the developer may want to implement a hard limit to the number of function calls that are invoked while in the automatic function call loop. With filters, the developer should be able to count the number of invocations and cancel after an arbitrary limit.
- **Telemetry** – The developer may want to log metadata about the loop (number of turns, the functions called via parallel function calling, etc.)

Below is a flow diagram of where the existing filters are and where the new filters need to exist for function calling

<img width="1364" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/1409190/86354539-bc26-491d-a80d-9dee9e84e93e">

**Comment by moonbox3** [comment] 2024-03-15 13:24
@matthewbolanos, for the second point: in both dotnet and Python (not sure about Java) there is a `max auto invoke attempts` option that is configured by the user. It defaults to 10 or 15, I believe, but this will make sure we're not stuck in an infinite loop. Isn't this achieving the same behavior as the proposed filters that you mention? If not, what is the delta? Thanks!

**Comment by lavinir** [comment] 2024-03-17 09:21
@matthewbolanos , today if a Function throws an exception, it is caught and swallowed, the exception message is extracted and added to the chat history as if it a 'regular' function response.
It would make sense if an exception was thrown, the function filters would receive the exception as well as the function response so that they are aware that an exception was thrown.

What do you think ?

**Comment by dmytrostruk** [comment] 2024-03-17 19:15
> @matthewbolanos , today if a Function throws an exception, it is caught and swallowed, the exception message is extracted and added to the chat history as if it a 'regular' function response. It would make sense if an exception was thrown, the function filters would receive the exception as well as the function response so that they are aware that an exception was thrown.
> 
> What do you think ?

@lavinir Thanks for feedback! I'm working on it at the moment in scope of this task: https://github.com/microsoft/semantic-kernel/issues/4896.
I expect to create a PR for it in the next couple of days.

**Comment by dmytrostruk** [comment] 2024-04-01 00:04
> It would make sense if an exception was thrown, the function filters would receive the exception as well as the function response so that they are aware that an exception was thrown.

PR for this functionality is here: https://github.com/microsoft/semantic-kernel/pull/5671

**Comment by lavinir** [comment] 2024-04-01 07:34
Thanks @dmytrostruk .
I'm not sure this addresses the functionality @matthewbolanos mentions on the first bullet of the issue description. 
There should be the ability for a function filter to terminate the auto invocation pipeline post function execution (OnFunctionInvokedFilter) so that the raw function response can be returned back to the caller. 

It looks like you removed the "Cancel" ability on post invocation so this won't be possible.
Also, for OnFunctionInvokingFilter, perhaps there needs to be another definition for early pipeline termination as the way Cancel works now 
* Adds an error response by the assistant (There should be a way to opt out of this in the Function Filter)
* Subsequent Functions (Tools) will still be called so the "Cancel" is really only "Skipping" the current tool call.

The 'early termination' functionality should be available for both Pre/Post function filters.

Does that make sense ?

**Comment by dmytrostruk** [comment] 2024-04-01 19:27
> I'm not sure this addresses the functionality @matthewbolanos mentions on the first bullet of the issue description.
> There should be the ability for a function filter to terminate the auto invocation pipeline post function execution (OnFunctionInvokedFilter) so that the raw function response can be returned back to the caller.

PR that I shared addresses the issue you mentioned in this comment:
<img width="714" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/13853051/c03b71d5-b0a3-4ffe-a9b7-851907bccc9a">

In terms of auto function calling pipeline, it's separate task, and most probably it will be achieved with new type of filters or by extending current type of filters in the future.

At the moment, functions are executed as isolated units, and they don't have information about execution context (whether it's auto function calling, direct call by developer or part of plan generated by Planner). Same for function filters.


> It looks like you removed the "Cancel" ability on post invocation so this won't be possible.

The problem is in the way how we handle cancellation and exceptions. In terms of isolated function execution, it doesn't make sense to cancel it after it was already executed. But it makes sense to cancel it to prevent execution of next function in pipeline. But since function itself and filter doesn't know about next function, it makes sense to move post invocation cancellation to the level where it will be useful. I still need to think where exactly this should be possible, maybe in new type of filter for function execution in pipeline.

> The 'early termination' functionality should be available for both Pre/Post function filters.

Could you please describe `early termination` scenario in more detail?

Thanks a lot for your feedback!

**Comment by miguelxdomingues** [comment] 2024-04-04 14:12
> @matthewbolanos, for the second point: in both dotnet and Python (not sure about Java) there is a `max auto invoke attempts` option that is configured by the user. It defaults to 10 or 15, I believe, but this will make sure we're not stuck in an infinite loop. Isn't this achieving the same behavior as the proposed filters that you mention? If not, what is the delta? Thanks!

Hello! I cannot find it in net 1.7.0 packages, can you please help? Thanks

**Comment by dingjianrui** [comment] 2024-04-25 00:57
> > I'm not sure this addresses the functionality @matthewbolanos mentions on the first bullet of the issue description.
> > There should be the ability for a function filter to terminate the auto invocation pipeline post function execution (OnFunctionInvokedFilter) so that the raw function response can be returned back to the caller.
> 
> @lavinir PR that I shared addresses the issue you mentioned in this comment: <img alt="image" width="714" src="https://private-user-images.githubusercontent.com/13853051/318542443-c03b71d5-b0a3-4ffe-a9b7-851907bccc9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMDY0OTksIm5iZiI6MTcxNDAwNjE5OSwicGF0aCI6Ii8xMzg1MzA1MS8zMTg1NDI0NDMtYzAzYjcxZDUtYjBhMy00ZmZlLWE5YjctODUxOTA3YmNjYzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDAwNDk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZjcxYzgwMTRiZTcwNjJjYTc1OTZmZmI5YzJmMzU4NjllYTY0YzFlMzE0MTU4YWRlMmZlOGJmMzczMGZkNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0KbuEPbatUkA5VE1g1cvW9to9xsiK2_4lmq0bxHq9-Y">
> 
> In terms of auto function calling pipeline, it's separate task, and most probably it will be achieved with new type of filters or by extending current type of filters in the future.
> 
> At the moment, functions are executed as isolated units, and they don't have information about execution context (whether it's auto function calling, direct call by developer or part of plan generated by Planner). Same for function filters.
> 
> > It looks like you removed the "Cancel" ability on post invocation so this won't be possible.
> 
> The problem is in the way how we handle cancellation and exceptions. In terms of isolated function execution, it doesn't make sense to cancel it after it was already executed. But it makes sense to cancel it to prevent execution of next function in pipeline. But since function itself and filter doesn't know about next function, it makes sense to move post invocation cancellation to the level where it will be useful. I still need to think where exactly this should be possible, maybe in new type of filter for function execution in pipeline.
> 
> > The 'early termination' functionality should be available for both Pre/Post function filters.
> 
> Could you please describe `early termination` scenario in more detail?
> 
> Thanks a lot for your feedback!

Hi @dmytrostruk, we do have the function call "early termination" requirement, for instance, the client side need the semi-structured data (JSON) returned from the function call for rendering the content into particular format. if the function call data is polished by the LLM, it's not possible to allow the client side to render the data in a particular format, but we do need the LLM to capture the user's intent and call the function automatically. thanks.

**Comment by dmytrostruk** [comment] 2024-04-25 01:03
@dingjianrui "Early termination" feature is implemented in this PR and will be merged soon: https://github.com/microsoft/semantic-kernel/pull/5936

**Closed** 2024-04-25 15:05 UTC
Labels: .NET, python, java, sk team issue, enhancement
