### ISSUE TITLE
Sample Code: OpenAI service failed to complete the prompt, APIConnectionError issue with Python 3.10

### ISSUE THREAD

**Issue by carterwilliamson** [microsoft/semantic-kernel#627] opened 2023-04-24 23:09 UTC
**Describe the bug**
Unable to run the sample code here: https://github.com/microsoft/semantic-kernel/blob/main/python/README.md

**To Reproduce**
1. Create new virtual environment `python -m venv venv`
2. `python -m pip install --upgrade semantic-kernel`
3. Create a `.env` file following these instructions: https://github.com/microsoft/semantic-kernel/blob/main/python/README.md#openai--azure-openai-api-keys
4. Copy this code - https://github.com/microsoft/semantic-kernel/blob/main/python/README.md#running-a-prompt into a file named __main__.py
5. Error: `Error: (<ErrorCodes.ServiceError: 6>, 'OpenAI service failed to complete the prompt', APIConnectionError(message='Error communicating with OpenAI', http_status=None, request_id=None))`

**Expected behavior**
Expected to see output like `Robots must not harm humans.`

**Desktop (please complete the following information):**
 - OS: Mac 12.6.1
 - IDE: VS Code
 - openai ==  0.27.4
 - semantic-kernel == 0.2.4.dev0
 - numpy == 1.24.3
 - python == 3.10.8

**Additional context**
Full error: `Error: (<ErrorCodes.ServiceError: 6>, 'OpenAI service failed to complete the prompt', APIConnectionError(message='Error communicating with OpenAI', http_status=None, request_id=None))`

No VPN enabled. New virtual environment.
Tried with my personal account as well as my company account. Both had same result.
Tried on a VPN, no luck.

Edit:

I was able to run the sample in an AWS ec2 instance with python 3.9. I then tested on my machine with a python:3.9 docker container which also worked. This appears to be an issue with python 3.10.

**Comment by poweihuang0817** [comment] 2023-05-09 06:19
Hello, I used Python 3.11.3 and it works. I didn't use venv but it does work. The issue you described is strange

**Comment by evchaki** [comment] 2023-05-16 21:05
@alexchaomander  can you take a look at this?

**Comment by alexchaomander** [comment] 2023-05-16 21:45
@carterwilliamson are you still running into this issue? I was able to get it to work fine using my Python 3.10 environment

**Comment by priya-27** [comment] 2023-05-18 10:07
Facing same issue with python 3.10 inside Codespaces for semantic kernel python notebooks, any fix ?

**Comment by 2662007798** [comment] 2023-05-18 10:08
Partly because of network problems, I switched to the Singapore server to work




阿生
***@***.***







                       
Original Email
                       
                     

Sender:"PRIYA BHIMJYANI"< ***@***.*** &gt;;

Sent Time:2023/5/18 18:07

To:"microsoft/semantic-kernel"< ***@***.*** &gt;;

Cc recipient:"2662007798"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

Subject:Re: [microsoft/semantic-kernel] Sample Code: OpenAI service failed tocomplete the prompt, APIConnectionError issue with Python 3.10 (Issue #627)




 
Facing same issue with python 3.10 inside Codespaces for semantic kernel python notebooks, any fix ?
 
&mdash;

**Comment by hot5auce** [comment] 2023-05-19 11:13
https://github.com/openai/openai-python/issues/278

**Comment by roshan-gopalakrishnan** [comment] 2023-05-24 07:13
If you are giving any org_id just comment it in the .env. It is optional.

**Comment by chenlucu** [comment] 2023-06-02 06:28
I got the same problem. I traced the error and found that it was not able to verify the local issuer certificate.  by add a config in the source code by ignoring

**Comment by priya-27** [comment] 2023-06-02 06:36
Yes, for me, the issue was I was using Azure open ai key and in the code in the sample python notebooks, there was a boolean flag variable for using azure open ai set to false by default.
<img width="369" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/109645740/19445cb7-fc3a-4353-9bd0-149c9af29ba8">


so if you Get this Error, either use open ai key or turn the boolean flag to true before using azure open ai key.

**Comment by bingokunkun** [comment] 2023-06-02 07:30
> 

It's no use to me : (

**Comment by bingokunkun** [comment] 2023-06-02 07:30
> I got the same problem. I traced the error and found that it was not able to verify the local issuer certificate. `Cannot connect to host xxxxxx.openai.azure.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]` So I added a config setting in the source code(openai/api_requestor.py line 586): <img alt="image" width="648" src="https://user-images.githubusercontent.com/4689385/242804325-e0619bc1-7821-4141-97f2-0fec76d8dab8.png"> This will ignore the verification of SSL certificate, and this fixed my problem.

It's no use to me : (

**Comment by chenlucu** [comment] 2023-06-02 08:31
> > I got the same problem. I traced the error and found that it was not able to verify the local issuer certificate. `Cannot connect to host xxxxxx.openai.azure.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]` So I added a config setting in the source code(openai/api_requestor.py line 586): <img alt="image" width="648" src="https://user-images.githubusercontent.com/4689385/242804325-e0619bc1-7821-4141-97f2-0fec76d8dab8.png"> This will ignore the verification of SSL certificate, and this fixed my problem.
> 
> It's no use to me : (

I think this error is generally the network problem, since it was not able to make a successful http request. (http_status=None, request_id=None, which means no http status and no request id). Might be an VPN problem, or the openai server blocked your request. You'd better debug and trace the error to find the exact reason.

**Comment by balasubramaniant95** [comment] 2023-06-06 07:47
It turned to an issue with proxy for me. Setting the proxy via the environment variables - HTTP_PROXY and HTTPS_PROXY did not work. 

I had to set the proxy using the below way

```
import openai

openai.proxy = {
    "http": "<HTTP_PROXY>",
    "https": "<HTTPS_PROXY >"
}
```

**Comment by matthewbolanos** [comment] 2023-06-12 12:18
> I _think_ I've run into the same SSL certificate something error.
> 
> And found [this solution on SO](https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify):
> 
> ```shell
> bash /Applications/Python*/Install\ Certificates.command
> ```
> 
> After restarting the Jupyter notebook kernel, things worked.

I ran into the same issue, but this solution fixed it on my end. Is this problem specific to Macbooks or Windows as well? @JJDawn, @2662007798, @priya-27, @bingokunkun, and @dandv, are all y'all on Macbooks?

**Comment by priya-27** [comment] 2023-06-12 13:10
Yes, on a mac

**Comment by 2662007798** [comment] 2023-06-14 07:01
> > _我想_我遇到了相同的SSL证书错误。
> > 并在 [SO 上找到了这个解决方案](https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify)：
> > ```shell
> > bash /Applications/Python*/Install\ Certificates.command
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 重新启动Jupyter笔记本内核后，事情开始了。
> 
> 我遇到了同样的问题。值得庆幸的是，这个解决方案解决了我的问题。这个问题是否也特定于Macbook或Windows？@JJDawn、@2662007798、@priya-27、@bingokunkun和@dandv，你们都在Macbook上吗？

no is windows

**Comment by garyjkuehn** [comment] 2023-07-26 11:16
Same error where identical code works on a PC but fails on my MacBook. (side by side test)
Macbook = 12.6.2
python = 3.10.2

fresh venv:

Package            Version
------------------ ----------
aiofiles           23.1.0
aiohttp            3.8.5
aiosignal          1.3.1
async-timeout      4.0.2
attrs              23.1.0
certifi            2023.7.22
charset-normalizer 3.2.0
click              8.1.6
frozenlist         1.4.0
idna               3.4
multidict          6.0.4
numpy              1.25.1
openai             0.27.8
pip                23.2.1
python-dotenv      1.0.0
regex              2023.6.3
requests           2.31.0
semantic-kernel    0.3.4.dev0
setuptools         58.1.0
tqdm               4.65.0
urllib3            2.0.4
yarl               1.9.2

**Comment by garyjkuehn** [comment] 2023-07-28 13:57
Corrected on the Mac by upgrading python to version 3.11.4. All other packages previously stated remain as-is within the new virtual environment.

**Comment by quangngoc** [comment] 2023-07-28 16:25
I have the same issue on Debian 11, python 3.10: `Error: (<ErrorCodes.ServiceError: 6>, 'OpenAI service failed to complete the chat', APIConnectionError(message='Error communicating with OpenAI', http_status=None, request_id=None))`
When using langchain in the same environment, it works

**Comment by shivam-51** [comment] 2023-08-29 05:27
Fixed on mac by running on Python 3.9 instead of 3.11. strange.

**Comment by GhimBoon** [comment] 2023-08-31 01:55
> It turned to an issue with proxy for me. Setting the proxy via the environment variables - HTTP_PROXY and HTTPS_PROXY did not work.
> 
> I had to set the proxy using the below way
> 
> ```
> import openai
> 
> openai.proxy = {
>     "http": "<HTTP_PROXY>",
>     "https": "<HTTPS_PROXY>"
> }
> ```

This worked for me. It seems that semantic kernel isn't referencing the env variables, and you have to manually set them.

**Comment by lemillermicrosoft** [comment] 2023-09-08 19:40
We understand the issue is related to the virtual environment configuration. No changes to be made in the python SDK at present.

**Closed by lemillermicrosoft** 2023-09-08 19:40 UTC
Labels: python
