### ISSUE TITLE
.Net: Support DI for Memory Connectors

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#6541] opened 2024-06-04 14:55 UTC
---
name: Feature request
about: Suggest an idea for this project

---

**Comment by matthewbolanos** [comment] 2024-06-07 09:58
Closing as a dupe of [#5278](https://github.com/microsoft/semantic-kernel/issues/5278)

**Closed by matthewbolanos** 2024-06-07 09:58 UTC
Labels: .NET, memory connector, memory
