### ISSUE TITLE
How to use copilot's text import function, I have an error reported

### ISSUE THREAD

**Issue by 13bbjxwz** [microsoft/semantic-kernel#966] opened 2023-05-12 02:35 UTC
How to use copilot's text import function, I have an error reported
![image](https://github.com/microsoft/semantic-kernel/assets/53102869/4745dd34-579d-47b0-9595-0234e90ac005)
![image](https://github.com/microsoft/semantic-kernel/assets/53102869/5598b6c0-8755-4479-b04c-7e5bfb3bda08)
The dialog function of copilot works fine.

**Comment by feiyun0112** [comment] 2023-05-13 14:02
did you set `ClientId` and `RedirectUri`? because you use "--user-collection"

https://github.com/microsoft/semantic-kernel/tree/main/samples/apps/copilot-chat-app/importdocument

**Comment by TaoChenOSU** [comment] 2023-05-16 18:18
Hello!

Thanks for reporting the issue!

The document import feature has been updated since you reported the issue. The user scoped collections have been replaced by chat session scoped collections.

Please refer to the README to see instructions on how to set up the `appsettings.json` file to allow the app to import documents to chat scoped collections.

Feel free to leave more questions here.

**Comment by 13bbjxwz** [comment] 2023-05-18 03:35
I have started the webapi service
![1684380427264](https://github.com/microsoft/semantic-kernel/assets/53102869/8788705a-4c7b-4931-ad5f-0faa13b5f573)
![1684380452410](https://github.com/microsoft/semantic-kernel/assets/53102869/c1e24607-9543-4835-a43b-4a1bf587d4c1)
The configuration file looks like this
![image](https://github.com/microsoft/semantic-kernel/assets/53102869/9b737826-97c5-4bd7-9495-c9fa696f42a0)
But I run dotnet run -- --file . \sample-docs\ms10k.txt prompted this
![1684380479208](https://github.com/microsoft/semantic-kernel/assets/53102869/a7304255-0a12-4ed0-9a52-f1080deb4ab4)
I don't know how to solve

**Comment by feiyun0112** [comment] 2023-05-18 05:29
did you setup WebApi Backend Server?

https://github.com/microsoft/semantic-kernel/tree/main/samples/apps/copilot-chat-app

you can debug WebApi to see what the problem is

https://github.com/microsoft/semantic-kernel/blob/main/samples/apps/copilot-chat-app/webapi/CopilotChat/Controllers/DocumentImportController.cs#LL69C44-L69C44

**Comment by TaoChenOSU** [comment] 2023-05-19 14:50
> this is work, ![4f910ff7c8a1c721656b8beef8ea35f](https://user-images.githubusercontent.com/53102869/239228200-b34baff8-4fdb-4401-9852-c4e4a86cf188.png)
> 
> It's still like this ![be6cb0913a319b3c2efe11b20e58b5b](https://user-images.githubusercontent.com/53102869/239228233-6e8c2e0e-d6de-41d9-a32f-588a8602c427.png)
> 
> I also encountered an error. I couldn't open Copolit on Google before, but I could still open it. The image above was opened using Microsoft's browser ![1](https://user-images.githubusercontent.com/53102869/239229191-9a7d4ab4-4f5f-4cf5-9478-52465321edae.png)

To resolve the SSL connection error, have you tried running the following command:
```
dotnet dev-certs https --trust
```

**Comment by TaoChenOSU** [comment] 2023-06-05 19:52
Closing now as it appears this issue has been resolved. Please reopen as needed.

**Closed by TaoChenOSU** 2023-06-05 19:52 UTC
Labels: samples
