### ISSUE TITLE
Python: add support for OpenAI and OpenAPI defined plugins

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#4554] opened 2024-01-10 15:27 UTC

**Comment by guy-microsoft** [comment] 2024-01-22 13:41
@shawncal Hi, is there an ETA for this feature?

**Comment by moonbox3** [comment] 2024-03-12 18:54
This is a duplicate of #5355. We will track the work in that work item. Closing this one.

**Closed by moonbox3** 2024-03-12 18:54 UTC
Labels: python, kernel, openapi
