### ISSUE TITLE
Long term memory not working in chatapp sample app

### ISSUE THREAD

**Issue by poweihuang0817** [microsoft/semantic-kernel#1033] opened 2023-05-17 06:21 UTC
**Describe the bug**
Due to token issue, the response from text completion will not be valid json.
SemanticChatMemory memory = SemanticChatMemory.FromJson(result.ToString());

    internal static async Task<SemanticChatMemory> ExtractCognitiveMemoryAsync(

{"items": [{"label": "workspaceName", "details": "SoP_High_Memory"}, {"label": "datasetName", "details": "SoP_High_Memory_0718"}, {"label": "columnName", "details": "AvgMemoryConsumption"}, {"label": "tableName", "details": "WabiAllHighRefresh0718"}, {"label...

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - IDE: [e.g. Visual Studio, VS Code]
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

**Comment by TaoChenOSU** [comment] 2023-05-17 16:02
Hello!

Thanks for reporting the issue!

Could you provide more details as to what you mean by token issue? Did the prompt exceed the token limit?

Please note that the models will not always generate valid Json blocks.

**Comment by poweihuang0817** [comment] 2023-05-17 19:27
warn: Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantMemoryStore[0]
      No vectors were found.
warn: Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantMemoryStore[0]
      No vectors were found.
warn: Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantMemoryStore[0]
      No vectors were found.
warn: Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantMemoryStore[0]
      No vectors were found.
warn: Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantMemoryStore[0]
      No vectors were found.
warn: Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantMemoryStore[0]
      Vectors not found
warn: Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantMemoryStore[0]
      Vectors not found
warn: Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantMemoryStore[0]
      No vectors were found.
warn: Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantMemoryStore[0]
      Vectors not found
warn: Microsoft.SemanticKernel.Connectors.Memory.Qdrant.QdrantMemoryStore[0]
      Vectors not found
      
      I'm suspecting there is some issue in memory setting.

**Comment by TaoChenOSU** [comment] 2023-05-17 19:36
Hi Powe!

Could you provide more details on how you encountered the errors/warnings? Logs or screenshots will help greatly.

**Comment by poweihuang0817** [comment] 2023-05-17 19:37
![image](https://github.com/microsoft/semantic-kernel/assets/131632377/d954d23d-61d6-4ce4-bf85-c36ef14bb3b1)

**Comment by craigomatic** [comment] 2023-06-02 23:57
This may have been caused by a bug that was impacting the Qdrant connector. This was resolved in #1313 

@poweihuang0817 if you have a spare moment to try with the latest code from the repository (I don't think the fix has made it to nuget yet) please let us know if the issue persists

**Comment by poweihuang0817** [comment] 2023-06-04 22:01
Hello craig and tao, I've mixed two issues up. The bigger question I want to report is that the long term memory would not be json format. GPT will not response as I requested. And then there will be json parsing error. I manage to reduce that by reducing the token.

**Comment by TaoChenOSU** [comment] 2023-06-09 20:46
Closing now as it appears this issue has been resolved. Please reopen as needed.

**Closed by TaoChenOSU** 2023-06-09 20:46 UTC
Labels: samples
