### ISSUE TITLE
.Net: Bug: "Missing required parameter: 'tools[0].function'.

### ISSUE THREAD

**Issue by nor0x** [microsoft/semantic-kernel#6825] opened 2024-06-19 15:30 UTC
Repro is here:
[BlazorApp1.zip](https://github.com/user-attachments/files/15903077/BlazorApp1.zip)

**Describe the bug**
I'm using Semantic Kernel with some KernelFunctions in a Blazor WebAssembly app. The kernel is built the following way with a registration of the Plugin:

```csharp
var kernelBuilder = Kernel.CreateBuilder();
kernelBuilder.AddOpenAIChatCompletion(_textModel, _apiKey, httpClient: new HttpClient());
kernelBuilder.Plugins.AddFromType<MyPlugin>();
var kernel = kernelBuilder.Build();
```

The Plugin in the repro is very basic and just logs stuff to the console
```csharp

[KernelFunction, Description("Log message to console")]
public void Log(string message)
{
	Console.WriteLine(message);
}
```

And this code is used to send the prompt to the LLM:
```csharp
var completionService = _kernel.GetRequiredService<IChatCompletionService>();

var result = await completionService.GetChatMessageContentAsync(
	$"Log '{Guid.NewGuid().ToString("N")}' to console!", 
	new OpenAIPromptExecutionSettings()
	{
		ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions,
		ChatSystemPrompt = _onlyFunctionPrompt,
		Temperature = 0.4,
	}
	, _kernel);
```

The call to `GetChatMessageContentAsync` produces the following error message:

```powershell
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Missing required parameter: 'tools[0].function'.
      Status: 400 (Bad Request)
      ErrorCode: missing_required_parameter
      
      Content:
      {
        "error": {
          "message": "Missing required parameter: 'tools[0].function'.",
          "type": "invalid_request_error",
          "param": "tools[0].function",
          "code": "missing_required_parameter"
        }
      }
      
      Headers:
      Content-Length: 199
      Content-Type: application/json
      
Microsoft.SemanticKernel.HttpOperationException: Missing required parameter: 'tools[0].function'.
Status: 400 (Bad Request)
ErrorCode: missing_required_parameter

Content:
{
  "error": {
    "message": "Missing required parameter: 'tools[0].function'.",
    "type": "invalid_request_error",
    "param": "tools[0].function",
    "code": "missing_required_parameter"
  }
}

Headers:
Content-Length: 199
Content-Type: application/json

 ---> Azure.RequestFailedException: Missing required parameter: 'tools[0].function'.
Status: 400 (Bad Request)
ErrorCode: missing_required_parameter

Content:
{
  "error": {
    "message": "Missing required parameter: 'tools[0].function'.",
    "type": "invalid_request_error",
    "param": "tools[0].function",
    "code": "missing_required_parameter"
  }
}

Headers:
Content-Length: 199
Content-Type: application/json

   at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
   at Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsAsync(ChatCompletionsOptions chatCompletionsOptions, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<RunRequestAsync>d__53`1[[Azure.Response`1[[Azure.AI.OpenAI.ChatCompletions, Azure.AI.OpenAI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8]], Azure.Core, Version=1.39.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8]].MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<RunRequestAsync>d__53`1[[Azure.Response`1[[Azure.AI.OpenAI.ChatCompletions, Azure.AI.OpenAI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8]], Azure.Core, Version=1.39.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8]].MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetChatMessageContentsAsync(ChatHistory chat, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.ChatCompletion.ChatCompletionServiceExtensions.GetChatMessageContentAsync(IChatCompletionService chatCompletionService, String prompt, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)
```

**Additional context**
please note that a `new HttpClient` is used because the app is running on Blazor WebAssembly and there is this bug here https://github.com/microsoft/semantic-kernel/issues/1792

I was not able to find a workaround yet, so this is currently a blocker for us

**Comment by dmytrostruk** [comment] 2024-06-19 23:32
@nor0x Thanks for reporting this issue. 
I tried to run your code and I wasn't able to reproduce this error using `gpt-4` model, I got new `Guid` in console. Could you please specify which AI model and version of Semantic Kernel you are using? Thanks!

**Comment by nor0x** [comment] 2024-06-20 06:42
thanks for your reply @dmytrostruk. I'm also using gpt-4 and I have updated the Nugets in my repro project which are the following:

```xml
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.6" PrivateAssets="all" />

    <PackageReference Include="Microsoft.KernelMemory.AI.OpenAI" Version="0.64.240619.1" />
    <PackageReference Include="Microsoft.KernelMemory.Core" Version="0.64.240619.1" />
    <PackageReference Include="Microsoft.KernelMemory.SemanticKernelPlugin" Version="0.64.240619.1" />
    <PackageReference Include="Microsoft.SemanticKernel.Plugins.Memory" Version="1.13.0-alpha" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.15.0" />
```

I still get the error mentioned above. Here is a screenshot:
![image](https://github.com/microsoft/semantic-kernel/assets/3210391/01e9257a-688a-44bc-8a6a-592301df112a)

**Comment by JasonHaley** [comment] 2024-06-21 15:46
I can recreate the issue but it isn't Semantic Kernel's code, but Azure.AI.OpenAIClient 1.0.0-beta.17.

The problem may be due to it running in web assembly.

It is failing in Semantic Kernel Connectors.OpenAI.ClientCore.cs line 403 but in a call that is supposed to serialize the funtions and only returning this in the response to OpenAI:
![image](https://github.com/microsoft/semantic-kernel/assets/4291604/d1810654-c145-426e-85fd-10cf2d3cf3ef)

**Comment by dmytrostruk** [comment] 2024-08-11 22:21
@nor0x Sorry for the delayed response. I can reproduce the issue using your application with Semantic Kernel v1.17.1 and Azure.AI.OpenAIClient v1.0.0-beta.17. It looks like the issue on Azure SDK side, for some reason information about `tools` is missing, however I debugged SK code, and we always provide the information about functions when function calling is enabled.

I also tested your application using new OpenAI SDK v2.0.0-beta.5 and I cannot reproduce it with this version. We are going to release updated OpenAI connector which uses OpenAI v2.0.0-beta.5 soon, here is a feature branch:
https://github.com/microsoft/semantic-kernel/tree/feature-connectors-openai

As soon as this feature branch will be released, this issue should be resolved. Thanks!

**Comment by dmytrostruk** [comment] 2024-09-09 22:59
@nor0x With updated OpenAI SDK and Semantic Kernel v1.18.2 this problem should be resolved, so I'm going to close this issue. In case you still able to reproduce it, please feel free to re-open this issue or create a new one. Thank you!

**Closed by dmytrostruk** 2024-09-09 22:59 UTC
Labels: bug, .NET, Ignite
