### ISSUE TITLE
Python: The basic_planner.py has a defect where it is not initializing the plan

### ISSUE THREAD

**Issue by rajib76** [microsoft/semantic-kernel#2703] opened 2023-09-04 20:17 UTC
**Describe the bug**

In the module python/semantic_kernel/planning/basic_planner.py, the __str__ function has a defect. The "self.plan" was never initialized in the init method

class Plan:
    """A simple plan object for the Semantic Kernel"""

    def __init__(self, prompt: str, goal: str, plan: str):
        self.prompt = prompt
        self.goal = goal
        self.generated_plan = plan

    def __str__(self):
        return f"Prompt: {self.prompt}\nGoal: {self.goal}\nPlan: {self.plan}"

**To Reproduce**

The below code will throw an error 

planner = BasicPlanner()

basic_plan = asyncio.run(planner.create_plan_async(goal=goal, kernel=kernel,prompt=PROMPT))
print("generated str " ,basic_plan.__str__)

AttributeError: 'Plan' object has no attribute 'plan'

**Expected behavior**
It should not throw an error if we initialize the plan

**Screenshots**
Traceback (most recent call last):
  File "/Users/joyeed/semantic_kernel/semantic_kernel_examples/examples/02_how_to_combine_semantic_native_function.py", line 68, in <module>
    print("generated str " ,basic_plan.__str__)
  File "/Users/joyeed/semantic_kernel/semantic_kernel_examples/venv/lib/python3.10/site-packages/semantic_kernel/planning/basic_planner.py", line 25, in __repr__
    return str(self)
  File "/Users/joyeed/semantic_kernel/semantic_kernel_examples/venv/lib/python3.10/site-packages/semantic_kernel/planning/basic_planner.py", line 22, in __str__
    return f"Prompt: {self.prompt}\nGoal: {self.goal}\nPlan: {self.plan}"
AttributeError: 'Plan' object has no attribute 'plan'

**Platform**
All

**Additional context**
None

**Comment by AdarshAcharya5** [comment] 2023-09-05 15:53
Yes. I think it's supposed to be self.generated_plan, not self.plan.

**Comment by rajib76** [comment] 2023-09-05 16:53
Actually no, the change will need to be there in the semantic_kernel in the return statement below. I can change and push it later in the week. The return statement below as slef.plan, that needs to be self.generated_plan

def __init__(self, prompt: str, goal: str, plan: str):
    self.prompt = prompt
    self.goal = goal
    self.generated_plan = plan

def __str__(self):
    return f"Prompt: {self.prompt}\nGoal: {self.goal}\nPlan: {self.plan}"

**Comment by rajib76** [comment] 2023-09-05 17:12
Excellent, this will solve it once merged

**Comment by lemillermicrosoft** [comment] 2023-09-05 23:04
Duplicate of #2660

**Closed by lemillermicrosoft** 2023-09-05 23:04 UTC
Labels: python, planner
