### ISSUE TITLE
.Net: Improve DI support for Memory

### ISSUE THREAD

**Issue by aaronpowell** [microsoft/semantic-kernel#5591] opened 2024-03-21 00:25 UTC
The Memory feature of SK uses a `MemoryBuilder` in a similar style to the `KernelBuilder`, but unlike the `KernelBuilder` it doesn't internally use an `IServiceCollection`, meaning it's harder to integrate with dependency injection and by extension .NET Aspire.

It would be nice if the `ISemanticTextMemory` and `IMemoryStore` implementations all supported DI in a similar fashion to working with the `IKernel`, with a method like the `AddSemanticKernel` and `AddAzureOpenAITextEmbedding` APIs.

**Comment by markwallace-microsoft** [comment] 2024-03-21 07:03
Hi @aaronpowell thanks for the feedback. We will be updating the memory connector packages and associated abstractions over the coming sprints. What you are requesting makes sense so we'll consider this as part of that work.

**Comment by matthewbolanos** [comment] 2024-06-07 10:00
Closing as a dupe of [#5278](https://github.com/microsoft/semantic-kernel/issues/5278)

**Closed by matthewbolanos** 2024-06-07 10:00 UTC
Labels: .NET, memory connector, memory
