### ISSUE TITLE
Unable to generate bot response. Details: Error: 400: => Invalid request: The request is not valid, HTTP status: 404

### ISSUE THREAD

**Issue by IhebGhazala** [microsoft/semantic-kernel#1608] opened 2023-06-20 16:45 UTC
**Describe the bug**
A clear and concise description of what the bug is.i have followed the read me file and changed it to use OpenAI in the appsettings.json the key is set but when i launch using yarn start in the copilot when i write in generates that error

**To Reproduce**
1. Go to semantic-kernel/samples/apps/copilot-chat-app/webapi
2. write dotnet user-secrets set "AIService:Key" "MY_AZUREOPENAI_OR_OPENAI_KEY"
3. continue with the read me steps when it launches write something

**Expected behavior**
it is supposed to generate  a response

**Desktop**
 - OS: windows 11
 - IDE: Visual Studio, VS Code
 - NuGet Package Version  0.1.0

**Comment by gitri-ms** [comment] 2023-07-04 00:08
@IhebGhazala - are you still experiencing this issue? If so, could you confirm the information I requested above?

**Comment by martinoez** [comment] 2023-07-05 14:39
Hello, we have the same issue with our deployment.
We are using AzureOpenAI. We have deployed a Static web app for the front-end and using an azure web app for the API.

Bug description:
When we type any prompt to CopilotChat, we receive an HTTP 400 error. On the web application, we get the following error;
_Unable to generate bot response. Details: Error: 400: Bad Request => Invalid request: The request is not valid, HTTP status: 404_

I confirmed the payload seems to be valid.

appsettings.json
`  "AIService": {
    "Type": "AzureOpenAI",
    "Endpoint": "myendpoint.openai.azure.com/", // ignored when AIService is "OpenAI"
    "Key": "mykey",
    "Models": {
      "Completion": "gpt-35-turbo", // For OpenAI, change to 'gpt-3.5-turbo' (with a period).
      "Embedding": "text-embedding-ada-002",
      "Planner": "gpt-35-turbo" // For OpenAI, change to 'gpt-3.5-turbo' (with a period).
    }
  },`

Do you have any idea what could be the problem?

**Comment by gitri-ms** [comment] 2023-07-05 19:07
@martinoez My first thought is to try prefixing the endpoint with `https://`. My next thought is to ensure that those models are all indeed available from your endpoint. I'll keep digging into what else it could be.

**Comment by martinoez** [comment] 2023-07-06 12:36
Hi Gina, thanks for getting back to me. The https:// prefix was already there, I just removed it when I posted the comment.
I confirmed on Azure OpenAI Studio, the models gpt-35-turbo and text-embedding-ada-002 are successfully deployed.

**Comment by dipteshbosedxc** [comment] 2023-07-11 12:02
Hello Gina,

I am also facing the same issue (local deployment for Azure OpenAI). Required models are deployed and is showing a green check mark. 

![image](https://github.com/microsoft/semantic-kernel/assets/138042190/600675bc-12c8-4cf8-b33c-9d5e51e90b0f)

**Error:**
fail: Microsoft.SemanticKernel.IKernel[0]
      Invalid request: The request is not valid, HTTP status: 404: Microsoft.SemanticKernel.AI.AIException: Invalid request: The request is not valid, HTTP status: 404
       ---> Azure.RequestFailedException: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.
      Status: 404 (Not Found)
      ErrorCode: DeploymentNotFound

      Content:
      {"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If 
you created the deployment within the last 5 minutes, please wait a moment and try again."}}

      Headers:
      OpenAI-Processing-Ms: REDACTED
      x-ms-client-request-id: b21ed67a-460f-4b99-82e8-2e6f1863b148
      apim-request-id: REDACTED
      Strict-Transport-Security: REDACTED
      X-Content-Type-Options: REDACTED
      x-ms-region: REDACTED
      Date: Tue, 11 Jul 2023 11:52:58 GMT
      Content-Length: 198
      Content-Type: application/json

         at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
         at Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsAsync(String deploymentOrModelName, ChatCompletionsOptions chatCompletionsOptions, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)         --- End of inner exception stack trace ---
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetChatResultsAsync(ChatHistory chat, ChatRequestSettings chatSettings, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetChatResultsAsTextAsync(String text, CompleteRequestSettings textSettings, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.SkillDefinition.SKFunction.<>c__DisplayClass24_0.<<FromSemanticConfig>g__LocalFunc|1>d.MoveNext()
fail: Microsoft.SemanticKernel.IKernel[0]
      Function call fail during pipeline step 0: ChatSkill.Chat. Error: Invalid request: The request is not valid, HTTP status: 404
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST https://localhost:40443/chat application/json 300 - 400 - text/plain;+charset=utf-8 1282.8842ms

**Comment by dipteshbosedxc** [comment] 2023-07-11 12:04
> Hello Gina,
> 
> I am also facing the same issue (local deployment for Azure OpenAI). Required models are deployed and is showing a green check mark.
> 
> ![image](https://user-images.githubusercontent.com/138042190/252656476-600675bc-12c8-4cf8-b33c-9d5e51e90b0f.png)
> 
> **Error:** fail: Microsoft.SemanticKernel.IKernel[0] Invalid request: The request is not valid, HTTP status: 404: Microsoft.SemanticKernel.AI.AIException: Invalid request: The request is not valid, HTTP status: 404 ---> Azure.RequestFailedException: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again. Status: 404 (Not Found) ErrorCode: DeploymentNotFound
> 
> ```
>   Content:
>   {"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If 
> ```
> 
> you created the deployment within the last 5 minutes, please wait a moment and try again."}}
> 
> ```
>   Headers:
>   OpenAI-Processing-Ms: REDACTED
>   x-ms-client-request-id: b21ed67a-460f-4b99-82e8-2e6f1863b148
>   apim-request-id: REDACTED
>   Strict-Transport-Security: REDACTED
>   X-Content-Type-Options: REDACTED
>   x-ms-region: REDACTED
>   Date: Tue, 11 Jul 2023 11:52:58 GMT
>   Content-Length: 198
>   Content-Type: application/json
> 
>      at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
>      at Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsAsync(String deploymentOrModelName, ChatCompletionsOptions chatCompletionsOptions, CancellationToken cancellationToken)
>      at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)         --- End of inner exception stack trace ---
>      at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetChatResultsAsync(ChatHistory chat, ChatRequestSettings chatSettings, CancellationToken cancellationToken)
>      at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetChatResultsAsTextAsync(String text, CompleteRequestSettings textSettings, CancellationToken cancellationToken)
>      at Microsoft.SemanticKernel.SkillDefinition.SKFunction.<>c__DisplayClass24_0.<<FromSemanticConfig>g__LocalFunc|1>d.MoveNext()
> ```
> 
> fail: Microsoft.SemanticKernel.IKernel[0] Function call fail during pipeline step 0: ChatSkill.Chat. Error: Invalid request: The request is not valid, HTTP status: 404 info: Microsoft.AspNetCore.Hosting.Diagnostics[2] Request finished HTTP/2 POST https://localhost:40443/chat application/json 300 - 400 - text/plain;+charset=utf-8 1282.8842ms

**Just an FYI** - Application Client ID from AD and the Azure OpenAI endpoint are from two different Azure subscriptions.

**Comment by TaoChenOSU** [comment] 2023-07-11 18:00
Thanks for reporting this issue and finding the solution!

Yes, for OpenAI you will need to specify the model name, whereas if you use Azure OpenAI you will need to specify the deployment name. I will update the ReadMe to reflect this.

**Comment by TaoChenOSU** [comment] 2023-07-11 21:48
Addressed by https://github.com/microsoft/semantic-kernel/pull/1956.

**Closed by TaoChenOSU** 2023-07-11 21:48 UTC
Labels: bug, copilot chat, copilot dev ux
