### ISSUE TITLE
Java: Core - Planning extension

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#1580] opened 2023-06-20 13:23 UTC

**Comment by d3r3kk** [comment] 2023-07-17 15:51
@johnoliver please break this down to the exact planners we are missing, and any examples/tests we need to implement as independent issues (@d3r3kk to help).

**Comment by d3r3kk** [comment] 2023-07-27 15:31
Two potential planners we need to implement:

- [ ] Stepwise Planner
- [ ] Basic Planner

**Comment by d3r3kk** [comment] 2023-08-29 16:01
Duplicate of #2478, closing this one.

**Closed by d3r3kk** 2023-08-29 16:01 UTC
Labels: java, sk team issue
