### ISSUE TITLE
.Net Agents: Rename `TerminationStrategy`

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-kernel#6787] opened 2024-06-17 22:37 UTC
Based on customer feedback via @matthewbolanos: `TerminationSTrategy` may be confusing term/name.

**Comment by matthewbolanos** [comment] 2024-06-17 22:51
Closing as a dupe of [#6759](https://github.com/microsoft/semantic-kernel/issues/6759)

**Closed by matthewbolanos** 2024-06-17 22:51 UTC
Labels: .NET, triage, enhancement, agents
