### ISSUE TITLE
The asynchronous function does not return Task

### ISSUE THREAD

**Issue by Alerinos** [microsoft/semantic-kernel#1265] opened 2023-05-29 22:54 UTC
We should rename the function or use the asychronic method.

```cs
public async Task<IAsyncEnumerable<string>> GetCollectionsAsync(CancellationToken cancellationToken = default)
```

https://github.com/microsoft/semantic-kernel/blob/9faa7e935007d8628035c95f009d51ee35b13ab2/dotnet/src/Connectors/Connectors.Memory.Qdrant/QdrantMemoryStore.cs#L67

If I'm right, I'll be happy to do PR

**Comment by stephentoub** [comment] 2023-05-30 00:57
It returns an `IAsyncEnumerable<string>`.  The naming convention is that such methods are named "Async" as well, since the work it performs is asynchronous and consumption is asynchronous.

**Comment by craigomatic** [comment] 2023-05-31 22:27
Closing as naming is by design. Feel free to reopen if there are additional questions related to this.

**Closed by craigomatic** 2023-05-31 22:27 UTC
Labels: kernel
