### ISSUE TITLE
.Net: Dotnet How we can override the api-version for TextEmbeddingAPI

### ISSUE THREAD

**Issue by jayendranarumugam** [microsoft/semantic-kernel#4451] opened 2024-01-02 15:22 UTC
I'm following azure apim to call the azureopenai as a proxy. While my approach is little different as I have my own `api-version`  which is not related to azure openai `api-version`

E.g, 
My api-version (apim) -> azure api-version (internally I'm handling inside apim logic)
20230101 -> 2023-07-01-preview 

I don't know how the api-versions are handled in the source code (semantic-kernel dotnet) Is there a way I can override the api-version parameter  ? I looked at `AddAzureOpenAITextEmbeddingGeneration` but I don't see any parameter for api-version that I can use to override 

Can some one help me on this ?

**Comment by matthewbolanos** [comment] 2024-01-02 19:13
Thanks for reporting! I'm going to close this as a dupe of #2833. We've marked it as a vnext item so it can be addressed soon.

**Closed by matthewbolanos** 2024-01-02 19:13 UTC
Labels: .NET, vnext
