### ISSUE TITLE
.Net: FunctionCallingStepwisePlanner error Expected 'MappingStart', got 'SequenceStart' (at Line: 26, Col: 3, Idx: 1203).

### ISSUE THREAD

**Issue by strikene** [microsoft/semantic-kernel#4296] opened 2023-12-15 05:41 UTC
**To Reproduce**

**I've tried not importing any plugins and the error is still there**

Here is my code 

<img width="1019" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/62022463/f48fad39-7943-48f6-ad12-e2d00f2cdc58">

            String FunctionCallingStepWisePlanner_initen = "Save the analysis report to onedrive, refer to C:\\A.pdf";

            FunctionCallingStepwisePlanner fcsp = new(new FunctionCallingStepwisePlannerConfig()
            {
                
            });
            FunctionCallingStepwisePlannerResult fcspre = await fcsp.ExecuteAsync(_SK_Kernel, FunctionCallingStepWisePlanner_initen);

Error Message: 
Expected 'MappingStart', got 'SequenceStart' (at Line: 26, Col: 3, Idx: 1203).
StackTrace:
   at YamlDotNet.Core.ParserExtensions.Require[T](IParser parser)
   at YamlDotNet.Core.ParserExtensions.Consume[T](IParser parser)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryDeserializer.Deserialize(Type tKey, Type tValue, IParser parser, Func`3 nestedObjectDeserializer, IDictionary result)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass4_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Microsoft.SemanticKernel.KernelFunctionYaml.FromPromptYaml(String text, IPromptTemplateFactory promptTemplateFactory, ILoggerFactory loggerFactory)
   at Microsoft.SemanticKernel.PromptYamlKernelExtensions.CreateFunctionFromPromptYaml(Kernel kernel, String text, IPromptTemplateFactory promptTemplateFactory)
   at Microsoft.SemanticKernel.Planning.FunctionCallingStepwisePlanner.<GeneratePlanAsync>d__5.MoveNext()
   at Microsoft.SemanticKernel.Planning.FunctionCallingStepwisePlanner.<ExecuteCoreAsync>d__2.MoveNext()
   at Microsoft.SemanticKernel.Planning.PlannerInstrumentation.<InvokePlanAsync>d__5`3.MoveNext()

**Platform**
 - OS: Windows
 - IDE:  Visual Studio
 - Language: C#
 - Source: 
 "Microsoft.Extensions.Http.Resilience" Version="8.0.0" 
 "Microsoft.KernelMemory.WebClient" Version="0.20.231211.3" 
 "Azure.ResourceManager.Billing" Version="1.0.1" 
 "Azure.ResourceManager.Resources" Version="1.6.0" 
 "Azure.ResourceManager.Subscription" Version="1.0.1" 
 "Azure.ResourceManager.Support" Version="1.0.1" 
 "Microsoft.SemanticKernel" Version="1.0.0-rc4" 
 "Microsoft.SemanticKernel.Connectors.Memory.Sqlite" Version="1.0.0-rc3" 
 "Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.0.0-rc4" 
 "Microsoft.SemanticKernel.Planners.Handlebars" Version="1.0.0-rc4" 
 "Microsoft.SemanticKernel.Planners.OpenAI" Version="1.0.0-rc4" 
 "Microsoft.SemanticKernel.Plugins.MsGraph" Version="1.0.0-rc4" 
 "Microsoft.SemanticKernel.Plugins.Web" Version="1.0.0-rc4" 
 "SharpToken" Version="1.2.12" 
 "Azure.AI.OpenAI" Version="1.0.0-beta.11" 
 "System.Text.Json" Version="8.0.0"

**Comment by MichaOnGit** [comment] 2023-12-15 08:50
This is resolved with this PR: https://github.com/microsoft/semantic-kernel/pull/4219

**Comment by stephentoub** [comment] 2023-12-15 14:05
> This is resolved with this PR: https://github.com/microsoft/semantic-kernel/pull/4219

@markwallace-microsoft, does this look familiar? Why would yaml parsing problems be related to function calling fixes?

**Comment by markwallace-microsoft** [comment] 2023-12-15 19:29
It's not a functional calling issue. The function calling planner uses a YAML prompt and that's where the issue is. This if fixed.

**Closed by markwallace-microsoft** 2023-12-15 19:29 UTC
Labels: .NET, triage
