### ISSUE TITLE
.Net: Bug: Unable to add the Microsoft.SemanticKernel NuGet package (version 1.31.0) to an Azure Function App targeting .NET 8

### ISSUE THREAD

**Issue by MuraliM** [microsoft/semantic-kernel#9854] opened 2024-12-01 18:51 UTC
**Describe the bug**
When adding the Microsoft.SemanticKernel NuGet package (version 1.31.0) to an Azure Function App targeting .NET 8, the application fails to process the blob when its uploaded. Failing to load Azure.Core: Could not load file or assembly 'System.Memory.Data, Version=6.0.0.0

**Azure Function** 

```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<AzureFunctionsVersion>v4</AzureFunctionsVersion>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.3.2" />
		<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.5.0" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="Microsoft.SemanticKernel" Version="1.31.0" />
	  <PackageReference Include="System.Memory.Data" Version="9.0.0" />
	</ItemGroup>
	<ItemGroup>
		<None Update="host.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="local.settings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</None>
	</ItemGroup>
</Project>
```

**Function trigger**

```
public class Function1
{
    [FunctionName("Function1")]
    public void Run([BlobTrigger("loandocuments/{name}", Connection = "AzureWebJobsStorage")]Stream myBlob, string name, ILogger log)
    {
        log.LogInformation($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {myBlob.Length} Bytes");

        
    }
}
```

**Error**

For detailed output, run func with --verbose flag.
[2024-12-01T18:40:41.485Z] An unhandled exception has occurred. Host is shutting down.
[2024-12-01T18:40:41.486Z] Azure.Core: Could not load file or assembly 'System.Memory.Data, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

**Additional information**
I have tried updating System.Memory.Data to version 8.0.0 as well to 9.0.0 and no luck.. 
I think the issue https://github.com/microsoft/semantic-kernel/issues/5226 is still occuring with System.Memory.Data. 
When I run `dotnet list package --include-transitive`
![Image](https://github.com/user-attachments/assets/c43104f9-07a9-4fd9-9676-7287397a5ecf)

**Comment by MunozVictor** [comment] 2024-12-04 12:50
Version 1.29.0 had a change in that reference and it doesn't work either:
- System.Memory.Data.1.0.2 -> System.Memory.Data.6.0.0.

Version 1.28.0 does work for me (.net 8).

**Comment by dmytrostruk** [comment] 2024-12-11 17:05
@MuraliM Thanks for reporting this issue. 

It looks like it's coming from Azure .NET SDK, since the only place where `System.Memory.Data` is directly referenced in Semantic Kernel is a unit test project (which I think we can remove at some point). 

I also found a similar issue here: https://github.com/Azure/azure-sdk-for-net/issues/47467

Could you please try to use these package versions and see if that works for you?

- Azure.Storage.Blobs 12.22.0 
- Azure.Storage.Common 12.21.0 
- Azure.Storage.Queues 12.20.0 
- Azure.KeyVaults.Secrets 4.6.0

Thank you!

**Comment by dmytrostruk** [comment] 2024-12-13 16:54
@MuraliM I created a PR to remove `System.Memory.Data` direct dependency from SK solution (https://github.com/microsoft/semantic-kernel/pull/9970), but as I mentioned in previous comment, I think the issue is occurring on Azure .NET SDK side. 

I'm going to close this issue, for more information please see my previous comment. Thanks!

**Closed by dmytrostruk** 2024-12-13 16:54 UTC
Labels: bug, .NET
