### ISSUE TITLE
.Net: Azure OpenAI deployment not found for hard-coded chat model in notebook

### ISSUE THREAD

**Issue by momuno** [microsoft/semantic-kernel#2643] opened 2023-08-30 00:47 UTC
**Describe the bug**
API deployed model does not exist.

**To Reproduce**
1. Go to '/dotnet/notebooks' and set configuration json to use Azure OpenAI.
2. In your Azure OpenAI account, deploy a custom named embeddings model (not the same name as the model) and a custom named chat model (not the same name as model)
3. Go to '/dotnet/notebooks/07-DALL-E-2.ipynb'
4. Run sections through "Generate a random image"
5. See error

**Expected behavior**
Section should run without error. Code is using an assumed embeddings and chat deployment models for Azure OpenAI, when user could create own deployment with different name. Solution likely to include deployed model names in the config file, and change code in notebook to reference that model, instead of a hard-coded assumed model.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/64985898/2bfd9949-fad0-4fbc-946e-036b0a1475a6)
![image](https://github.com/microsoft/semantic-kernel/assets/64985898/3a6fb24c-4ab7-4a46-bd34-d58aae0a083b)

**Additional context**
Similar issue encountered in Issue #2642

**Comment by sammiie** [comment] 2023-09-07 06:33
The issue you're describing appears to involve difficulties with an Azure OpenAI deployment not being found for a hard-coded chat model in a notebook. To address this issue, you can follow these general steps, but note that specific code and configurations will depend on your Azure setup and notebook environment:

Issue Explanation:

The problem is that the Azure OpenAI deployment is not being found for a hard-coded chat model in your notebook. This could be due to various reasons, such as incorrect configurations or permissions.

Solution:

Verify Azure Setup:

Ensure that your Azure environment is correctly configured with the necessary resources and permissions to access the OpenAI deployment.
Check Deployment Name:

Verify that the hard-coded deployment name in your notebook matches the actual name of the deployment in Azure. Ensure there are no typos or discrepancies.
Authentication and Authorization:

Ensure that you have the correct authentication and authorization mechanisms in place to access the Azure resources. This may involve using Azure service principals, tokens, or other authentication methods.
Resource Group and Location:

Confirm that the Azure resources related to your OpenAI deployment are in the correct resource group and location.
Network Configuration:

Check if there are any network or firewall restrictions that might be preventing your notebook from accessing the Azure resources.
Error Handling:

Implement robust error handling in your notebook code to capture and log any errors or exceptions that occur during the deployment lookup process.
Test with Azure SDK:

Consider using the Azure SDK for .NET to programmatically interact with your Azure resources, including the OpenAI deployment. This can help you ensure that the deployment is accessible and correctly configured.
Diagram Structure:

A simplified diagram illustrating the process of resolving the issue:

lua

+----------------------------------+
|    Azure OpenAI Deployment      |
|                                  |
|   +---------------------------+  |
|   |     Azure Environment     |  |
|   |                           |  |
|   | - Configuration           |  |
|   | - Permissions             |  |
|   | - Network Settings        |  |
|   |       ...                 |  |
|   +---------------------------+  |
|                                  |
|   +---------------------------+  |
|   |   Notebook Environment    |  |
|   |                           |  |
|   | - Hard-coded Deployment   |  |
|   |   Name                    |  |
|   | - Authentication          |  |
|   | - Error Handling          |  |
|   |       ...                 |  |
|   +---------------------------+  |
|                                  |
|   +---------------------------+  |
|   |    Azure SDK for .NET     |  |
|   |                           |  |
|   | - Programmatic Access     |  |
|   | - Validation              |  |
|   |       ...                 |  |
|   +---------------------------+  |
|                                  |
+----------------------------------+
In this diagram:

The "Azure OpenAI Deployment" is the target resource you're trying to access.
The "Azure Environment" includes Azure configurations, permissions, and network settings.
The "Notebook Environment" represents your notebook's code and configurations, including the hard-coded deployment name, authentication, and error handling.
The "Azure SDK for .NET" can be used to programmatically access Azure resources and validate the deployment's accessibility.

**Comment by Roybott** [comment] 2023-09-14 23:05
This can be fixed by changing the code in the kernel setup code block to use `builder.WithOpenAIChatCompletionService` instead of `WithOpenAITextCompletionService`.

**Closed** 2023-11-28 03:27 UTC
Labels: .NET, samples, sk team issue

**Comment by matthewbolanos** [comment] 2023-11-28 04:32
Closing so we can create new docs issues later.
