### ISSUE TITLE
Python: TypeError: Plan.__init__() got an unexpected keyword argument 'prompt'

### ISSUE THREAD

**Issue by taoari** [microsoft/semantic-kernel#2061] opened 2023-07-18 20:45 UTC
**Describe the bug**

When run `05-using-the-planner.ipynb`, got error: TypeError: Plan.__init__() got an unexpected keyword argument 'prompt'.

**To Reproduce**
1. Go to 'https://github.com/microsoft/semantic-kernel/tree/main/samples/notebooks/python'
2. jupyter notebook
3. run 05-using-the-planner.ipynb

**Expected behavior**

**Screenshots**

<img width="1100" alt="Screenshot 2023-07-18 at 1 44 15 PM" src="https://github.com/microsoft/semantic-kernel/assets/3815006/26a1a276-a312-4a36-9afd-2b09892b9dbe">

**Platform**
 - OS: [Mac]
 - IDE: [e.g. Jupyter Notebook]
 - Language: [Python]
 - Source: [e.g. main branch of repository]

**Additional context**

**Comment by febriy** [comment] 2023-07-20 07:30
I got the same issue and managed to fix it by changing the last line of the function `create_plan_async` within `basic_planner.py`

<img width="624" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/15272518/97d7ade8-0d21-4ae2-8190-43381af1d113">

**Comment by nolanhurlburt** [comment] 2023-07-23 17:42
Confirmed I experiencing this, but the above fix did not work for me.

**Comment by nolanhurlburt** [comment] 2023-07-23 18:52
Fixed by replacing plan.py with old plan.py:

from typing import Any

class Plan:
    # The goal that wants to be achieved
    goal: str

    # The prompt to be used to generate the plan
    prompt: str

    # The generated plan that consists of a list of steps to complete the goal
    generated_plan: Any

    def __init__(self, goal, prompt, plan):
        self.goal = goal
        self.prompt = prompt
        self.generated_plan = plan

**Comment by alexchaomander** [comment] 2023-07-25 13:07
Yeah this notebook needs to be updated with the latest from the plan object model that got landed. #1907

We'll also have new planners coming in soon! #1770 #1916

**Closed** 2023-11-28 02:15 UTC
Labels: bug, python, samples

**Comment by matthewbolanos** [comment] 2023-11-28 04:41
Closed because we will be deprecating the basic planner
