### ISSUE TITLE
.Net Message Format Inconsistency in Chat Completion Endpoint Handling

### ISSUE THREAD

**Issue by yuezhishun** [microsoft/semantic-kernel#5196] opened 2024-02-27 14:05 UTC
when making a request to the chat completion endpoint (v1/chat/completions), the message format is as follows:
For pure text messages:
```json
{
  "role": "user",
  "content": "Hello!"
}
```
For messages containing images or text:
```json
{
  "role": "user",
  "content": [
    {"type": "text", "text": "What’s in this image?"},
    {
      "type": "image_url",
      "image_url": {
        "url": "https://xxx.x.x/xxx.jpg"
      },
    },
  ]
}

```
To implement this distinction, the code at this point should be modified from
 `if (message.Items is { Count: > 0 })` to `if (message.Items is { Count: > 1 })`.
[here](https://github.com/microsoft/semantic-kernel/blob/2138724dcfcde5bbdaeb7be583699b711b737197/dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs#L919)

**Comment by dmytrostruk** [comment] 2024-03-11 13:01
@yuezhishun Could you please check this PR and verify if it covers this issue? https://github.com/microsoft/semantic-kernel/issues/5337

Based on changes in this PR, we will send plain string in case there is single text content or we will send array of contents in case it's not just single string.

**Comment by dmytrostruk** [comment] 2024-03-13 11:49
@yuezhishun It looks like this problem was fixed by PR I mentioned above. I'm going to close this issue, feel free to re-open it or create a new one in case of any further questions/issues. Thank you!

**Closed by dmytrostruk** 2024-03-13 11:49 UTC
Labels: .NET

**Comment by yuezhishun** [comment] 2024-03-16 03:24
@dmytrostruk   Thank you for your work, I've encountered the same issue as well[5337](https://github.com/microsoft/semantic-kernel/issues/5337)

**Comment by dmytrostruk** [comment] 2024-03-16 07:54
@yuezhishun Were you able to reproduce it using SK version 1.6.1+?
