### ISSUE TITLE
Cannot read properties of undefined (reading 'toLocaleLowerCase')

### ISSUE THREAD

**Issue by doolachen** [microsoft/semantic-kernel#912] opened 2023-05-10 07:11 UTC
I deployed the copilot-chat-app following the README steps. I got this error once I send any characters.
![image](https://github.com/microsoft/semantic-kernel/assets/53148827/f52c1856-d9ff-40f6-a679-a89fcc9f956e)

**Comment by hunk-fe** [comment] 2023-05-11 02:58
I get the same problem!

**Comment by daiping0323** [comment] 2023-05-11 03:04
i got same problem

**Comment by evchaki** [comment] 2023-05-11 21:02
@doolachen , thank you for bringing this up.  We have logged a bug and are working to fix it.

**Comment by doolachen** [comment] 2023-05-12 08:50
@evchaki , I really appreciate the effort you put into fixing this bug. I'm curious to know what caused this error. I followed the deployment process as documented, and it seems like others didn't encounter this issue. Did I miss a step somewhere, or could there be some underlying project-specific issues at play?

**Comment by cooptest** [comment] 2023-05-12 09:13
@doolachen There is no such error when I switch to the edge browser, but the message robot does not reply

**Comment by cooptest** [comment] 2023-05-12 09:14
@doolachen 换成edge浏览器不会报错，但是给机器人发消息它不回复

**Comment by hathind-ms** [comment] 2023-05-16 18:05
Can you please confirm the following:
1. AI endpoints are set in `appsettings.json` - This needs to be updated in 2-3 places based on whether you want to use Planner or not. Check these sections - `Completion`, `Embedding` and/or `Planner`
2. Key for AI resource is set - This can either be set using `dotnet secrets` or updated in `appsettings.json` in 2-3 places similar to step 1
3. Confirm your webapi is running at : https://localhost:40443/probe
4. You have a valid .env file with following values set:
```
REACT_APP_BACKEND_URI=https://localhost:40443/
REACT_APP_AAD_CLIENT_ID={Your Application (client) ID}
REACT_APP_AAD_AUTHORITY=https://login.microsoftonline.com/common
```

Reference this ReadMe for more details: https://github.com/microsoft/semantic-kernel/blob/main/samples/apps/copilot-chat-app/README.md

**Comment by teresaqhoang** [comment] 2023-05-16 21:56
Hi @doolachen, @hunk-fe, @daiping0323, @forczc, AND @cooptest, do you see a screen that says `Semantic Kernel service up and running` when you navigate to https://localhost:40443/probe?

**Comment by cooptest** [comment] 2023-05-17 07:13
Deploy and install locally (http://localhost:3000)

I can start successfully and get a response

You cannot log in to Copilot chat with the same account as the Azure subscription, you need to change another account, otherwise an error will be reported no matter what content is sent

Is there any plan to deploy the configuration on the server? Now it can only be accessed on localhost, but I want to access it through the server IP on the Internet

**Comment by Tangroo** [comment] 2023-05-18 04:14
> Hi @doolachen, @hunk-fe, @daiping0323, @forczc, AND @cooptest, do you see a screen that says `Semantic Kernel service up and running` when you navigate to https://localhost:40443/probe?
> 
> Also, are you guys following the README exactly (spinning up the webapi and WebApp locally) or are you using one of the deployment templates to deploy Semantic Kernel to Azure?

I get the same problem! I deployed strictly according to README. Is it necessary to deploy the Semantic Kernel to Azure and then deploy the copilot chat locally?Or simply deploy the copilot chat app locally?

**Comment by Tangroo** [comment] 2023-05-18 07:56
https://github.com/microsoft/semantic-kernel#sample-apps-
In the second requirement, it says that you need to configure the Azure Functions Core Tools. Do you need to deploy this tool locally ahead of time? Despite installing the tool, I still see the same error message.

**Comment by teresaqhoang** [comment] 2023-05-18 19:22
> > Hi @doolachen, @hunk-fe, @daiping0323, @forczc, AND @cooptest, do you see a screen that says `Semantic Kernel service up and running` when you navigate to https://localhost:40443/probe?
> > Also, are you guys following the README exactly (spinning up the webapi and WebApp locally) or are you using one of the deployment templates to deploy Semantic Kernel to Azure?
> 
> I get the same problem! I deployed strictly according to README. Is it necessary to deploy the Semantic Kernel to Azure and then deploy the copilot chat locally?Or simply deploy the copilot chat app locally?

Hey @Tangroo, It is not necessary to deploy the webapi to Azure, running it locally should work fine! 

> In the second requirement, it says that you need to configure the Azure Functions Core Tools. Do you need to deploy this tool locally ahead of time? Despite installing the tool, I still see the same error message.

Copilot Chat actually doesn't require Azure Functions Core Tools (our bad, we should update the documentation). The other sample apps leverage the KernelHttpServer as the service API, and it's deployed against Azure Function Runtime, so those tools are required there to run the service locally. Copilot uses an Asp.Net web application to expose SK APIs.

**Comment by teresaqhoang** [comment] 2023-05-18 19:51
@cooptest @Tangroo  I'm unable to reproduce this issue. Do you guys have the latest changes pulled? We've pushed a lot of bug fixes in the past week

**Comment by Tangroo** [comment] 2023-05-19 01:19
> @cooptest @Tangroo I'm unable to reproduce this issue. Do you guys have the latest changes pulled? We've pushed a lot of bug fixes in the past week

Yes, I pulled the latest code and cloned it again yesterday. However, if I redeploy it, I will still report the same error.

**Comment by teresaqhoang** [comment] 2023-05-19 01:20
> > @cooptest @Tangroo I'm unable to reproduce this issue. Do you guys have the latest changes pulled? We've pushed a lot of bug fixes in the past week
> 
> Yes, I pulled the latest code and cloned it again yesterday. However, if I redeploy it, I will still report the same error.

Can you send a screenshot of the error? We no longer have the getAudienceMemberForId method, so I’m wondering what the stack looks like now.

**Comment by Tangroo** [comment] 2023-05-19 01:27
![image](https://github.com/microsoft/semantic-kernel/assets/48377330/62566041-a82b-4e14-80b4-54d16b314254)
the webapi started successfully.
![image](https://github.com/microsoft/semantic-kernel/assets/48377330/b91bced4-3823-4784-8ece-e423b18de0aa)
When the webapp is just opened, it is also in a normal state
![image](https://github.com/microsoft/semantic-kernel/assets/48377330/e2ab72ab-43e5-43e0-865f-106dfd6f9a18)
When I send a message to it, it jumps directly to this error page

**Comment by forczc** [comment] 2023-05-19 02:21
> 
I have the same issue as @Tangroo, and I noticed there is an error with this request on the network.
ur: https://localhost:40443/chat
![image](https://github.com/microsoft/semantic-kernel/assets/13718643/76740446-1cb9-4ffd-8cf8-ab5a781178fc)

**Comment by coopliu** [comment] 2023-05-19 04:08
> @cooptest @Tangroo I'm unable to reproduce this issue. Do you guys have the latest changes pulled? We've pushed a lot of bug fixes in the past week

No, I changed a Microsoft account and logged in to Copilot Chat again, it can run successfully and receive a reply
<img width="956" alt="1" src="https://github.com/microsoft/semantic-kernel/assets/55048424/60677515-13bf-4c8b-81aa-38d063245379">

**Comment by coopliu** [comment] 2023-05-19 04:11
> @cooptest @Tangroo I'm unable to reproduce this issue. Do you guys have the latest changes pulled? We've pushed a lot of bug fixes in the past week

No, I changed a Microsoft account and logged in to Copilot Chat again, it can run successfully and receive a reply
<img width="956" alt="1" src="https://github.com/microsoft/semantic-kernel/assets/55048424/60677515-13bf-4c8b-81aa-38d063245379">

**Comment by forczc** [comment] 2023-05-19 05:36
> > @cooptest @Tangroo I'm unable to reproduce this issue. Do you guys have the latest changes pulled? We've pushed a lot of bug fixes in the past week
> 
> No, I changed a Microsoft account and logged in to Copilot Chat again, it can run successfully and receive a reply <img alt="1" width="956" src="https://user-images.githubusercontent.com/55048424/239434718-60677515-13bf-4c8b-81aa-38d063245379.png">

me too

**Comment by teresaqhoang** [comment] 2023-05-19 21:18
What accounts were you using before? Personal accounts or enterprise accounts? @forczc @Tangroo

**Comment by Tangroo** [comment] 2023-05-20 10:04
> What kind of accounts were you using before? Personal? @forczc @Tangroo

I used the user for authentication to log in before, and then I reported an error. According to the method provided by @coopliu, I changed the login account, but there was a new error report, 404, how to solve this problem?
![image](https://github.com/microsoft/semantic-kernel/assets/48377330/f091b32d-35e4-47df-a11e-685bf6b891f5)

**Comment by forczc** [comment] 2023-05-20 11:28
> What kind of accounts were you using before? Personal? @forczc @Tangroo

yes，Personal

**Comment by Codingsaikou** [comment] 2023-05-22 08:05
I changed a Microsoft account and logged in to Copilot Chat again, but cant connect to <api.openai.com> 

fail: Microsoft.SemanticKernel.IKernel[0]
      Error executing request, max retry count reached. Reason: System.Net.Http.HttpRequestException
      System.Net.Http.HttpRequestException:  (api.openai.com:443)
       ---> System.Net.Sockets.SocketException (10060): 
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Reliability.DefaultHttpRetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
warn: Microsoft.SemanticKernel.IKernel[0]

**Comment by teresaqhoang** [comment] 2023-05-22 23:09
> I changed a Microsoft account and logged in to Copilot Chat again, but cant connect to <api.openai.com>
> 
> fail: Microsoft.SemanticKernel.IKernel[0] Error executing request, max retry count reached. Reason: System.Net.Http.HttpRequestException System.Net.Http.HttpRequestException: (api.openai.com:443) ---> System.Net.Sockets.SocketException (10060): at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) at System.Net.Sockets.Socket.g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at Microsoft.SemanticKernel.Reliability.DefaultHttpRetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) warn: Microsoft.SemanticKernel.IKernel[0]

Hi @Codingsaikou, this seems like a separate issue related to OpenAI capacity. OpenAI might have been throttled at the time you tried to connect. Can you try again? If the issue persists, please open another issue thread for help. Thanks!

**Comment by teresaqhoang** [comment] 2023-05-22 23:10
Hi @doolachen, @hunk-fe, @daiping0323, @forczc, @cooptest, I just merged a fix into main to solve this issue.

Turns out Msal doesn't require "name" as a required property on the account, so when it was undefined (as it is for most personal accounts), we'd see the null pointer error when trying to parse the value on the front and backend.

I've implemented a solution that falls back to the account username if the name property is empty, so your personal accounts should work with Copilot chat now.

Thanks for calling this to our attention and all of your help in debugging! Closing this issue. Please reopen if the problem persists.

**Closed by teresaqhoang** 2023-05-22 23:10 UTC
Labels: samples
