### ISSUE TITLE
Azure OpenAI with GitHub repo sample show 500 when retrieving models

### ISSUE THREAD

**Issue by mahomedalid** [microsoft/semantic-kernel#326] opened 2023-04-04 21:59 UTC
**Describe the bug**

When trying the example, if using Azure OpenAI endpoint it will return 500 when retrieving models.

**Expected behavior**

* It should handle the 500 error and show a clear message to the user instead of parsing the JSON.
* I would want to know if there is an issue with my Azure OpenAI resource or how to solve it.

**Screenshots**

![image](https://user-images.githubusercontent.com/952392/229931788-5f9c78f0-78b1-43fd-a103-4a385577d5da.png)

**Desktop (please complete the following information):**
 - OS: Windows WSL Linux (Bash)

**Additional context**

* Azure OpenAI Pricing: Standard created few days ago in East US.
* I have deployed 3 models, including davinci-003

More context in the next message of discussion.

**Comment by mahomedalid** [comment] 2023-04-04 22:02
When troubleshooting and looking into the documentation there is no mention of the endpoint `/models` inhttps://learn.microsoft.com/en-us/rest/api/cognitiveservices/azureopenaistable. I do see `deployments` https://learn.microsoft.com/en-us/rest/api/cognitiveservices/azureopenaistable/deployments/list?tabs=HTTP which could get similar information. Probably deployments replaced models?

If I do `curl  -v 'https://letsmeet-test.openai.azure.com//openai/models?api-version=2023-03-15-preview' -H 'api-key: XXX'`  I get the `HTTP/2 500`, but if I do `curl  -v 'https://letsmeet-test.openai.azure.com//openai/deployments?api-version=2023-03-15-preview'` instead I get:

```
{
  "data": [
    {
      "scale_settings": {
        "scale_type": "standard"
      },
      "model": "text-davinci-003",
      "owner": "organization-owner",
      "id": "text-davinci-003",
      "status": "succeeded",
      "created_at": 1680644079,
      "updated_at": 1680644079,
      "object": "deployment"
    },
    {
      "scale_settings": {
        "scale_type": "standard"
      },
      "model": "text-ada-001",
      "owner": "organization-owner",
      "id": "text-ada-001",
      "status": "succeeded",
      "created_at": 1680644132,
      "updated_at": 1680644132,
      "object": "deployment"
    },
    {
      "scale_settings": {
        "scale_type": "standard"
      },
      "model": "code-davinci-002",
      "owner": "organization-owner",
      "id": "emme",
      "status": "succeeded",
      "created_at": 1680644168,
      "updated_at": 1680644168,
      "object": "deployment"
    }
  ]
```

**Comment by bexxx** [comment] 2023-04-06 07:53
This issue was caused by a configuration issue on the service side and has been fixed yesterday. No action is needed on the client side. Please retry again.

**Comment by craigomatic** [comment] 2023-04-11 20:09
We've added more meaningful error messages, closing for now. Please reopen/reach out if you continue to see issues.

**Closed by craigomatic** 2023-04-11 20:09 UTC

**Comment by mahomedalid** [comment] 2023-04-13 20:59
Thank you this is great work @craigomatic !. Continuing the conversation, I got it working, but I missed one step (copying .env.example to .env), the error was just a 404 (it was trying to get into `undefined/api/...`), I think we can do a better job catching this issues for final users.

On ServiceConfig.tsx, line 31 (`const sk = useSemanticKernel(process.env.REACT_APP_FUNCTION_URI as string);`) we can potentially check if the REACT_APP_FUNCTION_URI is properly set, and if not either have a default (localhost:7071) or throw an error that the user needs to setup the `.env` file. 

I can help with a PR, let me know if that would be helpful or not.
