### ISSUE TITLE
Python: add truncation methods to chat history

### ISSUE THREAD

**Issue by eavanvalkenburg** [microsoft/semantic-kernel#4463] opened 2024-01-03 13:27 UTC
In a long chat conversation you want to be able to truncate the message history, either by deleting specific messages, oldest messages or by replacing (a set of) messages with a summary, this should be easy and transparent. Related to #3559

**Comment by eavanvalkenburg** [comment] 2024-02-25 15:31
This can now be started on the Chathistory object, @matthewbolmatt this would be a great one for the community to pick up!

**Comment by alliscode** [comment] 2024-06-19 20:53
This is a dupe of #6770

**Closed by alliscode** 2024-06-19 20:53 UTC
Labels: python, sk team issue, chat history
