### ISSUE TITLE
.Net: Allow native functions to have complex types for inputs/outputs

### ISSUE THREAD

**Issue by nschuessler** [microsoft/semantic-kernel#1978] opened 2023-07-12 18:53 UTC
Currently only primitive types are supported for native code skills (i.e. string, int, double).
Would a PR be allowed to add checks to `SkFunction.cs` to allow generic collections of primitive types (short term), until a more general solution is available?

i.e. ideally you would test if the return type is serializable to JSON (if that is what the concern is), even if it a customer provided class/struct.

Example:

```
+        if (targetType.IsGenericType &&
+            targetType.GetGenericTypeDefinition().Equals(typeof(List<>)) &&
+            GenericTypeConverter.TryGetParameterConverters(targetType, out TypeConverter[]? parameterConverters))
+        {
+            return new ListTypeConverter(targetType, parameterConverters);
+        }
```

```
public static bool TryGetParameterConverters(Type targetType, [NotNullWhen(true)] out TypeConverter[]? converters)
    {
        converters = null;

        Type[] typeParameters = targetType.GetGenericArguments();
        if (typeParameters != null && typeParameters.Length > 0)
        {
            int count = 0;
            TypeConverter[] tempConverters = new TypeConverter[typeParameters.Length];
            for (int i = 0; i < typeParameters.Length; i++)
            {
                TypeConverter? temp = SKFunction.GetTypeConverter(typeParameters[i]);
                if (temp == null)
                {
                    break;
                }

                tempConverters[i] = temp;
                count++;
            }

            if (count == typeParameters.Length)
            {
                converters = tempConverters;
            }
        }

        return converters != null;
    }
```

**Comment by nschuessler** [comment] 2023-07-14 14:54
@shawncal What is the usual triage turn around time? thx

**Comment by nacharya1** [comment] 2023-07-24 23:30
@shawncal  - can you take a look into this?

**Comment by ambrose-leung** [comment] 2023-10-23 14:51
This may be related to: https://github.com/microsoft/semantic-kernel/issues/2081

**Comment by SergeyMenshykh** [comment] 2023-12-12 23:52
@nschuessler there have been many improvements introduced for functions since the issue was created. Today, generic collections with primitives are supported.
<img width="678" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/68852919/6783631e-aecf-4a7c-8362-e6a4d30fdd9e">
Please get latest version of SK [RC3](https://www.nuget.org/packages/Microsoft.SemanticKernel/) ATM and let us know if it covers your scenario,

**Comment by SergeyMenshykh** [comment] 2023-12-14 21:27
Closing the issue for now, assuming the problem is resolved. Feel free to reopen it if that's not the case.

**Closed by SergeyMenshykh** 2023-12-14 21:27 UTC
Labels: enhancement, kernel, v1
