### ISSUE TITLE
.Net: Bug: Exception thrown with chatCompletionService.GetStreamingChatMessageContentsAsync

### ISSUE THREAD

**Issue by deepinderdeol** [microsoft/semantic-kernel#9333] opened 2024-10-18 23:37 UTC
Seeing the exception below with this call: 
**chatCompletionService.GetStreamingChatMessageContentsAsync(_skChatHistory, executionSettings, kernel)**

- I see this issue with latest nuget package version 1.24.1
- The issue is not repro with package version 1.20.0

**Exception:**
System.TypeLoadException
  HResult=0x80131522
  Message=Method 'GetAsyncEnumerator' in type 'OpenAI.Chat.InternalAsyncStreamingChatCompletionUpdateCollection' from assembly 'OpenAI, Version=2.1.0.0, Culture=neutral, PublicKeyToken=b4187f3e65366280' does not have an implementation.
  Source=OpenAI
  StackTrace:
   at OpenAI.Chat.ChatClient.CompleteChatStreamingAsync(IEnumerable`1 messages, ChatCompletionOptions options, CancellationToken cancellationToken)
   at Azure.AI.OpenAI.Chat.AzureChatClient.CompleteChatStreamingAsync(IEnumerable`1 messages, ChatCompletionOptions options, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<>c__DisplayClass16_1.<GetStreamingChatMessageContentsAsync>b__0()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.RunRequest[T](Func`1 request)
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<GetStreamingChatMessageContentsAsync>d__16.MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<GetStreamingChatMessageContentsAsync>d__16.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)

**Comment by RogerBarreto** [comment] 2024-10-25 08:13
Hi @deepinderdeol, thanks for the issue.

At first looks like you are referencing a different version of OpenAI SDK than the expected `2.1.0-beta.1` in your solution.

Can you provide more details on the references and how I can reproduce the above error? Possibly including the code for chathistory , settings and the kernel ?

Thanks

**Comment by RogerBarreto** [comment] 2024-11-06 15:27
Closing this as no more feedback was provided and potentially the OpenAI version used was previous to `2.1.0-beta.1`

**Closed by RogerBarreto** 2024-11-06 15:27 UTC
Labels: bug, .NET, follow up
