### ISSUE TITLE
Python: C# porting for multiple native function arguments

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#1977] opened 2023-07-12 17:39 UTC
Porting #1195 to Python makes native functions much easier to use.

**Comment by evchaki** [comment] 2023-08-01 16:39
@joowon-dm-snu  - thank you for bringing this up.  It would be great to have this in Python.  Feel free to do a PR to bring this over.

**Comment by matthewbolanos** [comment] 2023-10-26 10:01
Closing as a duplicate of [#3307](https://github.com/microsoft/semantic-kernel/issues/3307)

**Closed by matthewbolanos** 2023-10-26 10:01 UTC
Labels: enhancement, python
