### ISSUE TITLE
.Net: LLamaSharp Connector

### ISSUE THREAD

**Issue by KSemenenko** [microsoft/semantic-kernel#3235] opened 2023-10-18 19:49 UTC
I think it would be a good idea to add a C# connector for LLamaSharp

https://github.com/SciSharp/LLamaSharp
I think it might be a good idea

**Comment by dmytrostruk** [comment] 2023-10-19 12:14
@KSemenenko Thanks for creating this issue! 
It's definitely a good idea to add LLamaSharp Connector, which would be compatible with Semantic Kernel. At the moment, we are trying to find mechanism how to add new Connectors and Plugins to SK ecosystem in a scalable way. 

As the amount of possible extensions for SK grows really fast, we encourage Connector and Plugin authors to add new implementations in their own repositories and share it with us. It will allow us to keep this repository for SK Core functionality only, while authors can manage and structure their code for SK extensions in a best possible way.

Please let us know if this makes sense. We would be happy to see new SK Connector! :)

**Comment by stephentoub** [comment] 2023-10-19 13:20
> We would be happy to see new SK Connector! :)

The cited repo already provides one:
https://github.com/SciSharp/LLamaSharp/tree/master/LLama.SemanticKernel
https://www.nuget.org/packages/LLamaSharp.semantic-kernel

It'd be good, though, if SK folks could review it to ensure it's following desired conventions, implementing functionality in the desired way, etc.

**Comment by matthewbolanos** [comment] 2024-01-05 21:34
Going to close this as a duplicate of https://github.com/microsoft/semantic-kernel/issues/1215. We'll be working with the LlamaSharp contributors to make sure their connector works as expected with Semantic kernel.

**Closed by matthewbolanos** 2024-01-05 21:34 UTC
Labels: .NET, ai connector
