### ISSUE TITLE
Python: Run prompt function exception

### ISSUE THREAD

**Issue by Jasper-zh** [microsoft/semantic-kernel#5407] opened 2024-03-11 04:31 UTC
Error occurred while invoking function tell_joke_about: Error occurred while invoking function tell_joke_about: ("<class 'semantic_kernel.connectors.ai.open_ai.services.open_ai_chat_completion.OpenAIChatCompletion'> service failed to complete the prompt", AuthenticationError("Error code: 401 - {'error': {'message': 'Incorrect API key provided: gpt-3.5-*urbo. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}"))

My key is valid. I can use OpenAI's API.

**Comment by eavanvalkenburg** [comment] 2024-03-11 10:23
@Jasper-zh looks like something did go wrong with the key, which version are you using and can you share a code snippet?

**Comment by Jasper-zh** [comment] 2024-03-12 01:25
If you use version 0.9, you will have the same error as above.

```
"""
semantic_kernel_example -

Author: zhang
Date: 2024/3/11
"""
import semantic_kernel as sk
from semantic_kernel.connectors.ai.open_ai import OpenAIChatCompletion
from semantic_kernel.prompt_template.input_variable import InputVariable
import asyncio
import os
from dotenv import load_dotenv, find_dotenv


_ = load_dotenv(find_dotenv())

kernel = sk.Kernel()

api_key = os.getenv('OPENAI_API_KEY')
service_id = "my-gpt3"
model = OpenAIChatCompletion(
    service_id,
    "gpt-3.5-turbo",
    api_key,
    ""
)

kernel.add_service(model)

req_settings = kernel.get_service(service_id).get_prompt_execution_settings_class()(service_id=service_id)
req_settings.max_tokens = 2000
req_settings.temperature = 0.7
req_settings.top_p = 0.8
prompt_template_config = sk.PromptTemplateConfig(
    template="tell me a joke about {{$input}}",
    name="tell_joke_about",
    template_format="semantic-kernel",
    input_variables=[
        InputVariable(name="input", description="The user input", is_required=True),
    ],
    execution_settings=req_settings,
)

tell_joke_about = kernel.create_function_from_prompt(
    function_name="tell_joke_about",
    plugin_name="tell",
    prompt_template_config=prompt_template_config,
)


if __name__ == '__main__':
    result = asyncio.run(kernel.invoke(tell_joke_about, sk.KernelArguments(input="hello world")))
    print(result)
```

After that, I changed it to the 0.4 version, and it was normal.
```
import semantic_kernel as sk
from semantic_kernel.connectors.ai.open_ai import OpenAIChatCompletion
import os
import asyncio


from dotenv import load_dotenv, find_dotenv
_ = load_dotenv(find_dotenv())

kernel = sk.Kernel()

api_key = os.getenv('OPENAI_API_KEY')
model = OpenAIChatCompletion(
    "gpt-3.5-turbo",
    api_key
)

kernel.add_text_completion_service("my-demo", model)
tell_joke_about = kernel.create_semantic_function("tell me a joke about {{$input}}")

if __name__ == '__main__':
    result = asyncio.run(kernel.run_async(
            tell_joke_about,
            input_str="Hello world"
        ))
    print(result)
```

**Comment by Kushalamummigatti** [comment] 2024-03-12 11:57
> If you use version 0.9, you will have the same error as above.
> 
> ```
> """
> semantic_kernel_example -
> 
> Author: zhang
> Date: 2024/3/11
> """
> import semantic_kernel as sk
> from semantic_kernel.connectors.ai.open_ai import OpenAIChatCompletion
> from semantic_kernel.prompt_template.input_variable import InputVariable
> import asyncio
> import os
> from dotenv import load_dotenv, find_dotenv
> 
> 
> _ = load_dotenv(find_dotenv())
> 
> kernel = sk.Kernel()
> 
> api_key = os.getenv('OPENAI_API_KEY')
> service_id = "my-gpt3"
> model = OpenAIChatCompletion(
>     service_id,
>     "gpt-3.5-turbo",
>     api_key,
>     ""
> )
> 
> kernel.add_service(model)
> 
> req_settings = kernel.get_service(service_id).get_prompt_execution_settings_class()(service_id=service_id)
> req_settings.max_tokens = 2000
> req_settings.temperature = 0.7
> req_settings.top_p = 0.8
> prompt_template_config = sk.PromptTemplateConfig(
>     template="tell me a joke about {{$input}}",
>     name="tell_joke_about",
>     template_format="semantic-kernel",
>     input_variables=[
>         InputVariable(name="input", description="The user input", is_required=True),
>     ],
>     execution_settings=req_settings,
> )
> 
> tell_joke_about = kernel.create_function_from_prompt(
>     function_name="tell_joke_about",
>     plugin_name="tell",
>     prompt_template_config=prompt_template_config,
> )
> 
> 
> if __name__ == '__main__':
>     result = asyncio.run(kernel.invoke(tell_joke_about, sk.KernelArguments(input="hello world")))
>     print(result)
> ```
> 
> After that, I changed it to the 0.4 version, and it was normal.
> 
> ```
> import semantic_kernel as sk
> from semantic_kernel.connectors.ai.open_ai import OpenAIChatCompletion
> import os
> import asyncio
> 
> 
> from dotenv import load_dotenv, find_dotenv
> _ = load_dotenv(find_dotenv())
> 
> kernel = sk.Kernel()
> 
> api_key = os.getenv('OPENAI_API_KEY')
> model = OpenAIChatCompletion(
>     "gpt-3.5-turbo",
>     api_key
> )
> 
> kernel.add_text_completion_service("my-demo", model)
> tell_joke_about = kernel.create_semantic_function("tell me a joke about {{$input}}")
> 
> if __name__ == '__main__':
>     result = asyncio.run(kernel.run_async(
>             tell_joke_about,
>             input_str="Hello world"
>         ))
>     print(result)
> ```

Am facing the same issue. Could you help me how to change the version to 0.4? Steps to be followed.

**Comment by Jasper-zh** [comment] 2024-03-13 11:11
> Am facing the same issue. Could you help me how to change the version to 0.4? Steps to be followed.

If you are using pycharm, you can set the version at the place where the module is added, or uninstall it directly and then install it in the specified version.
![image](https://github.com/microsoft/semantic-kernel/assets/45052303/953ecd17-fd6d-4b14-82ae-851300e229ca)

**Comment by Kushalamummigatti** [comment] 2024-03-13 11:48
> > Am facing the same issue. Could you help me how to change the version to 0.4? Steps to be followed.
> 
> If you are using pycharm, you can set the version at the place where the module is added, or uninstall it directly and then install it in the specified version. ![image](https://private-user-images.githubusercontent.com/45052303/312428178-953ecd17-fd6d-4b14-82ae-851300e229ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjg1NzAsIm5iZiI6MTcxMDMyODI3MCwicGF0aCI6Ii80NTA1MjMwMy8zMTI0MjgxNzgtOTUzZWNkMTctZmQ2ZC00YjE0LTgyYWUtODUxMzAwZTIyOWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDExMTExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZGU3ZTYzZTAzYjM0NTQ2OGQ0OWViNzkxZDMzNzUzNTUyNzZkNmViZjAyMDIyMGU1ZWJhMWY5ZmYzMzQzMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mx1o6jzFygaJpwMGUjToW63vG9LXx1Ya0sEq1g1qduQ)

I uninstalled and installed the 0.4 dev version as am using VS code. But with this version i have issue AttributeError: 'Kernel' object has no attribute 'add_service' when i run the below code 

if selectedService == Service.OpenAI:
    from semantic_kernel.connectors.ai.open_ai import OpenAIChatCompletion

    api_key, org_id = sk.openai_settings_from_dot_env()
    service_id = "default"
    kernel.add_service(
        OpenAIChatCompletion(service_id=service_id, ai_model_id="gpt-3.5-turbo-1106", api_key=api_key, org_id=org_id),
    )
elif selectedService == Service.AzureOpenAI:
    from semantic_kernel.connectors.ai.open_ai import AzureChatCompletion

    deployment, api_key, endpoint = sk.azure_openai_settings_from_dot_env()
    service_id = "default"
    kernel.add_service(
        AzureChatCompletion(service_id=service_id, deployment_name=deployment, endpoint=endpoint, api_key=api_key),
    )

Could you please help me solve this?

**Comment by eavanvalkenburg** [comment] 2024-03-13 21:28
Hey @Jasper-zh I think the issue is that the OpenAIChatCompletion class now requires keyword args, so this change should do it:
```python
model = OpenAIChatCompletion(
    service_id=service_id,
    ai_model_id="gpt-3.5-turbo",
    api_key=api_key,
)
```

**Comment by moonbox3** [comment] 2024-03-13 23:43
The solution has been provided, closing the issue.

**Closed by moonbox3** 2024-03-13 23:43 UTC
Labels: python

**Comment by Jasper-zh** [comment] 2024-03-14 02:51
@Kushalamummigatti Because the older version did not have these functions, the two versions were written completely differently

**Comment by Jasper-zh** [comment] 2024-03-14 02:53
thank you. @moonbox3
