### ISSUE TITLE
.Net: Automatic conversion of enums is not working as expected

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#5045] opened 2024-02-16 09:36 UTC
**Describe the bug**
Automatic conversion of enums is not working as expected.

**To Reproduce**
1. Function has a default value provided for the `pipelineType` argument
2. Trying to invoke the function without `pipelineType` defined, but this doesn't work for the current [GetConverter implementation](https://github.com/microsoft/semantic-kernel/blob/1dfb45f6fef91f08ac32b1950660db637b76d140/dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromMethod.cs#L673C57-L673C69). When I called the plugin again and provided a value for `pipelineType`, the `EnumConverter` was loaded and invoked just fine. Part of me feels like this code should be able to check if the argument is defined with a default value, and if it is trust the compiler and just return the converter instead of returning null and throwing the "Unable to find type converter" function.

**Expected behavior**
Update: ok, I discovered that by excluding the pipelineType argument from the KernelArguments entirely since the value being added was an empty string, that this worked. So I wonder if the logic should follow "if the input is empty, but the parameter has a default value, and there can be a converter for the parameter type, trust the compiler runtime"
 
Update #2: I just did a check and removed the default value from the function definition, when I tried to invoke it without a value, the Kernel successfully got angry with me  "InvokePlugin Failed with an error. Missing argument for function parameter 'pipelineType'"

**Comment by SergeyMenshykh** [comment] 2024-02-23 16:49
The issue is caused by a try to set null to not nullable parameter with default value:
```C#
[Fact]
public async Task ItCanWorkWithEnumsAsync()
{
    DayOfWeek? actualDay = null;

    // Arrange
    void DoSmth(DayOfWeek day = DayOfWeek.Wednesday)
    {
        actualDay = day;
    }

    var function = KernelFunctionFactory.CreateFromMethod(DoSmth);

    // Scenario #1 - no argument supplied - success
    var result = await function.InvokeAsync(this._kernel, new KernelArguments());
    Assert.Equal(DayOfWeek.Wednesday, actualDay);

    // Scenario #2 - null argument supplied - failure
    await Assert.ThrowsAsync<ArgumentOutOfRangeException>(() => function.InvokeAsync(this._kernel, new KernelArguments() { ["day"] = null }));
}
```
SK follows the C# function-calling semantic, which does not allow calling functions with null arguments for non-nullable parameters.   
  
There are two ways to solve this issue, both of which are aligned with C# function-calling semantics:  
1. Either avoid passing null arguments for non-nullable parameters.  
2. Or, make the parameter nullable.  
   
Therefore, closing the issue for now.

**Closed by SergeyMenshykh** 2024-02-23 16:49 UTC
Labels: .NET, triage
