### ISSUE TITLE
.Net: Empty Response for AutoInvokeKernelFunctions using AddAzureOpenAIChatCompletion

### ISSUE THREAD

**Issue by harryaultavanade** [microsoft/semantic-kernel#4674] opened 2024-01-19 11:40 UTC
**Describe the bug**
Currently I'm getting an Empty response back when using ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions and AzureOpenAI. If I use OpenAI the response is completely fine and the function is executed. Model Version: 1106-Preview.

**Note:** if I ask a query that doesn't trigger the function, it executes fine. 

**To Reproduce**

```
IKernelBuilder kernelBuilder = Kernel.CreateBuilder();
            

  kernelBuilder.Services.AddAzureOpenAIChatCompletion(
      deploymentName: "gpt-4", 
      endpoint: "xxx",              
      apiKey: "xxx"       
  );
  kernelBuilder.Plugins.AddFromType<AccountPlugin>();
  

  Kernel kernel = kernelBuilder.Build();

  OpenAIPromptExecutionSettings settings = new() { ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions };
  IChatCompletionService chatCompletionService = kernel.GetRequiredService<IChatCompletionService>();

  ChatHistory chatMessages = new("""
  You are an Account Bot
  """);

  chatMessages.AddUserMessage("Show me my Accounts");

  OpenAIPromptExecutionSettings openAIPromptExecutionSettings = new()
  {
      ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions
  };

```
**Expected behavior**
The Function is invoked and the response given. 

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: .NET
 - Source: Microsoft.SemanticKernel Version="1.1.0" 

**Additional context**

**Comment by harryaultavanade** [comment] 2024-01-19 12:13
FYI May be a Duplicate of https://github.com/microsoft/semantic-kernel/issues/4671, but they haven't specified the LLM Interface

**Comment by fleccy** [comment] 2024-01-19 12:22
I'm having a similar issue to this. Which region is it that you're using? I'm experiencing problems with France Central (which didn't work at all until this morning with a tool error) and Sweden Central using 1106-preview. It works occasionally but falls over and just keeps asking how it can assist me today.

**Comment by harryaultavanade** [comment] 2024-01-19 12:37
Was also using Sweden! - Just swapped to East US which seems to be working!

Still a bug / issue though, would expect the response / behavior to be standardized for all regions...

**Comment by stephentoub** [comment] 2024-01-19 13:11
Can you share a self-contained runnable repro of the problem? The repro provided is incomplete (eg it's missing AccountPlugin). Thanks.

**Comment by fleccy** [comment] 2024-01-19 15:53
> > Can you share a self-contained runnable repro of the problem? The repro provided is incomplete (eg it's missing AccountPlugin). Thanks.
> 
> For Brevity Sake I've simplified it - https://github.com/harryaultavanade/Example---Copy/tree/master
> 
> **Reproducible Steps:**
> 
> * Azure Open AI (UkSouth) -> Model GPT4-1106-Preview
> * Message -> "Fetch Account Information Harry"
> * Output -> {}
> 
> -- Repeat in West US with the same model and version -- Output-> "User [harry@email.com](mailto:harry@email.com)"

I can replicate the issue and it's the same as mine. Oddly enough one of my old test sites was running fine under RC3 so as a test I cloned your repo, removed Semantic.Kernel.Core 1.1.0 and downgraded Microsoft.SemanticKernel 1.1.0 to 1.0.0-rc3 and replaced your code in Chat.cs with the below and it now works:

`using Microsoft.AspNetCore.Mvc;
using Microsoft.SemanticKernel;
using System.ComponentModel;
using Microsoft.SemanticKernel.AI.ChatCompletion;
using Microsoft.SemanticKernel.Connectors.AI.OpenAI;

namespace Controllers.Chat
{
    [Route("api/[controller]")]
    [ApiController]
    public class ChatController : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetChatAsync([FromQuery] string message)
        {


            // Create a kernel with OpenAI chat completion
            var kernelBuilder = new KernelBuilder();
            

            kernelBuilder.AddAzureOpenAIChatCompletion(
                deploymentName: "gpt-4", modelId: "gpt-4",
                endpoint: "xxx",              
                apiKey: "xxx"
            );
            kernelBuilder.Plugins.AddFromType<AccountPlugin>();
            

            Kernel kernel = kernelBuilder.Build();




            OpenAIPromptExecutionSettings settings = new() { FunctionCallBehavior = FunctionCallBehavior.AutoInvokeKernelFunctions };
            IChatCompletionService chatCompletionService = kernel.GetRequiredService<IChatCompletionService>();

            ChatHistory chatMessages = new("""
            You are an Account Planner
            """);

            chatMessages.AddUserMessage(message);

            OpenAIPromptExecutionSettings openAIPromptExecutionSettings = new()
            {

                FunctionCallBehavior = FunctionCallBehavior.AutoInvokeKernelFunctions
            };

            var result = await chatCompletionService.GetChatMessageContentAsync(
               chatMessages,
               executionSettings: openAIPromptExecutionSettings,
               kernel: kernel); ;

            return Ok(result.ToString());
        }

    }

    public class AccountPlugin
    {


        [KernelFunction, Description("Fetch Account Information")]
        [return: Description("Account Information")]
        public string SearchAccountInformation(
            [Description("Email Address for User, {username}@email.com")]
        string AccountName
    
            )
        {

            return "Account Name ID: " + AccountName;

        }
    }

}
`

**Comment by matthewbolanos** [comment] 2024-01-19 17:48
@crickman, can you confirm if this is a duplicate of the issue you're working on?

**Comment by crickman** [comment] 2024-01-29 17:53
@harryaultavanade - Over the past week or two, the Azure team has addressed some **region specific issues** with the function calling models...specifically around `tools` vs `functions` support.  

GPT function calling models are expected to support both the legacy `functions` spec as well as the new `tools` spec.  The reason this surfaces in newer SK packages is because the older packages are still relying on `functions` spec while the newer SK package has migrated to the `tools` spec.

Ultimately, this should be resolved by the Azure team by now:

In the `tools` version, the following response was provided (in our isolated repro)
```
{
  "role": "assistant"
}
```

Today, we are getting a full response:

```
{
  "role": "assistant",
  "tool_calls": [
    {
      "id": "call_qi46sfWTfAsLeAi1zxwoRDIj",
      "type": "function",
      "function": {
        "name": "search_hotels",
        "arguments": "{\"features\":\"beachfront,free breakfast\",\"location\":\"San Diego\",\"max_price\":300}"
      }
    }
  ]
}
```

Can you please confirm if this issue is persisting for you with the current SK package.

**Closed** 2024-01-30 13:09 UTC
Labels: .NET, kernel
